- .gitignore
- .teamcity/readme.md
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Web.Tests/EdFi.Ods.AdminApp.Web.Tests.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/packages.config
1. Consistently install Microsoft.NET.Test.Sdk 16.4.0 across test projects in order to account for missing automatic binding redirect generation. All changes in this first commit were automated by NuGet during installation of that package. This addresses situations where tests will pass on one developer's machine or another inconsistently. It has been reported as a problem with the Moq testing library but is in fact an issue with NetStandard 2.0 in combination with .NET Framework: https://github.com/dotnet/standard/issues/481 Note that the suggested msbuild tags for test projects in that referenced Issue are in fact handled by referencing the Test SDK.
2. Remove .gitignore rule for `.../WebRoot/post-install-readme.txt` as this file is no longer produced during builds.
3. The TeamCity …
> [AA-943] Adjustments after bulk copy from old repo

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/EditApplicationCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/EditApplicationCommand.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/EdFi.Ods.AdminApp.Web.Tests.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/packages.config
- Updated EdFi.Admin.DataAccess to EdFi.Suite3.Admin.DataAccess across the solution. The EdFi.Common was specifically updated to 5.0.0 on EdFi.Ods.AdminApp.Management.csproj.
- Updated EdFi.Security.DataAccess to EdFi.Suite3.Security.DataAccess across the solution.
- Updated EdFi.LoadTools to EdFi.Suite3.LoadTools across the solution.
- Updated EdFi.Common 3.4.0 to EdFi.Common 5.0.0 in the Web.Tests project
- Added EdFi.Suite3.Common 5.0.0 in the Web, Web.Tests, Management and Management.Tests project
- Refactored EditApplicationCommand and corresponding tests to use CreateApplicationEducationOrganization instead of CreateEducationOrganizationAssociation instead because of the method being renamed. 
- All the other version and dependency package updates are automatically …
> [AA-901] - Latest platform nuget packages(.net core 3.1 compatible) update on admin app

- .teamcity/_Self/templates/BuildAndTestTemplate.kt
- build.ps1
To meet the behavior of TeamCity builds prior to the creation of the Ed-Fi-Alliance-OSS organization, the TeamCity build favors the OnPremisesRelease configuration.
Note also some adjustments to the build.ps1 script to better reflect the current Build Configurations matrix in the *.sln file itself, to ensure all the intended tests can be found and run.
> [AA-944] Favor OnPremisesRelease Configuration

- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
AppCommon build [1094](https://intedfitools1.msdf.org/buildConfiguration/SharedLibraries_EdFiInstallerAppCommon/86578) includes change for urlrewrite broken link. Package build locally on my machine and verified the updated link showed in the prerequisites.psm1 file.
> [AA-1010] - Bump AppCommon to Include Version With New UrlRewrite Download Link

- Application/EdFi.Ods.AdminApp.Web.Tests/Controllers/OdsInstanceSettingsController/WhenRunningBulkUpload.cs
- Application/EdFi.Ods.AdminApp.Web.Tests/Infrastructure/IO/WhenConfiguringFileImport.cs
- Application/EdFi.Ods.AdminApp.Web/App_Start/StartupBase.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/BulkImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/FileImportConfiguration.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/BulkUploadJob.cs
Per discussion on this and related tickets, ODS 3.x experiences multithreading issues under high load such as during Learning Standards and Bulk Load operations. ODS 5.x is understood to be safe from this issue. To mitigate the problem when running these two high load operations from Admin App, the guidance was to throttle the number of simultaneous connections. Thankfully we can do so only against 3.x, allowing the original intended degree of parallelism to remain in place for ODS 5+ users.
Note that we are particularly pessimistic here in our exception handling for the Learning Standards aspect, because the setting is selected during Admin App's own startup process, and we need to be as polite as possible during startup to allow the system to come up at all. Here we favor a pessimistic …
> [AA-1016] Pessimistic simultaneous API calls against ODS 3.x

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/BulkUploadValidationTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/Controllers/OdsInstanceSettingsController/WhenRunningBulkUpload.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/BulkFileUploadModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstanceSettings/BulkLoad.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstanceSettings/_SaveBulkUploadCredentialsForm.cshtml
- Added a new SaveBulkUploadCredentialsModel with only ApiKey and ApiSecret properties. Added the SaveBulkUploadCredentialsModelValidator and validation rules for the ApiKey and ApiSecret properties.
- Refactored to use SaveBulkUploadCredentialsModel instead of BulkFileUploadModel in the BulkUploadValidationTests, WhenRunningBulkUpload and SaveBulkLoadCredentials.
- Added a partial view SaveBulkUploadCredentialsForm by extracting the form from the BulkLoad view.
- Added BulkUploadValidationTests to the tests project in order to test the new validation rules added to the SaveBulkUploadCredentialsModel.
> [AA-1013] - Bulk Upload works with an unrelated API key and secret

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/AddApplicationCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/EditApplicationCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/RegisterOdsInstanceCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/TestingHelper.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/ApplicationExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/AddApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/EditApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/RegisterOdsInstanceModel.cs
- Added MaximumApplicationNameLength property to ApplicationExtensions to have a common place to check for the maximum application name length.
- Added the ApplicaitonNameMaxLength validation rule to RegisterOdsInstanceModel
- Added empty string check for newInstanceDatabaseName in the BeAUniqueInstanceName validation rule to avoid checking uniqueness against an empty string.
- Added an overload for Sample function to take in both a prefix and length to return a random string with the prefix and of the specified length.
- Refactored the RegisterOdsInstanceTests to factor in the disposal of the connection object in the validator in subsequent validation rules. In order to avoid the situation, SetupSequence is used to provide a different connection object for each call to …
> [AA-1012] - Error creating new instance with non default database name

- EdFi.Suite3.Installer.AdminApp/install.ps1
- EdFi.Suite3.Installer.AdminApp/test.ps1
Final PR for 2.0.0 release that will bump version of AA web nupkg used in the installer. This PR might also contain small changes found during RC testing that didn't deserve to go through RC testing again
edited: removed merge warning and now ready for review/merge
> [AA-971] - Final Installer 2.0.0 Version Bumps

- Application/EdFi.Ods.AdminApp.Management.Aws.Tests/EdFi.Ods.AdminApp.Management.Aws.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure.UnitTests/EdFi.Ods.AdminApp.Management.Azure.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure/EdFi.Ods.AdminApp.Management.Azure.csproj
- Application/EdFi.Ods.AdminApp.Management.OnPrem.Tests/EdFi.Ods.AdminApp.Management.OnPrem.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/App.config
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Setup/SqlServerCloudOdsDatabaseSecurityConfiguratorTester.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Management.UnitTests/EdFi.Ods.AdminApp.Management.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/EdFi.Ods.AdminApp.Web.Tests.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/app.config
- Application/EdFi.Ods.AdminApp.Web.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Web.base.config
- Application/EdFi.Ods.AdminApp.Web/packages.config
Opening this PR in order to witness the CI build. I'll update this description when it is ready for review.
.NET Core work will involve a lot of dependency upgrades. This PR simply gets the simplest and safest upgradable dependencies upgraded so that they are out of the way once .NET Core upgrade work itself truly begins.
We'll also want to be consistently working across the team with VS2019, so this also addresses the fact that VS Test Explorer's own breaking changes changed the behavior of NUnit `[Explicit]` attributes such that they are unusable until a future NUnit release addresses that problem.
> [AA-1050] simple package upgrades

- Application/EdFi.Ods.AdminApp.Management/Database/Commands/DeleteVendorCommand.cs
- Moved deletion of users after deletion of applications to avoid the reference constraint exception while deleting a vendor.
> [AA-1047] Multi instance mode - Exception deleting vendor when there's an application assigned

- Application/EdFi.Ods.AdminApp.Web/Scripts/site.js
Refactored to use the ajax method in get form instead of load method in order to avoid the json results to show up on the view in case of a session expired scenario. The load() method tries to set the HTML contents if a successful response is detected even though the data received is not HTML.
> [AA-1078] - Remove plain text message when session is no longer valid

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetFileImportCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/ClaimSetFileImportCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/SharingModel.cs
- Application/EdFi.Ods.AdminApp.Management/Instances/BulkRegisterOdsInstancesCommand.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/InputFileExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetFileImportModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/BulkRegisterOdsInstancesModel.cs
-  Removed IBulkRegisterOdsInstancesModel as the interface is not being used in the BulkRegisterOdsInstancesCommand. Removed usage of IbulkRegisterOdsInstancesModel. Removed unused using directives.
- Refactored to move the SharingModel methods to InputFileExtensions and renamed to make the connection to SharingModel more explicit. Refactored the Deserialize method to use the GetMemoryStream method available in InputFileExtensions.
- Refactored to remove IClaimSetFileImportModel and corresponding usages to pass only the SharingModel content to the Execute method of the ClaimSetFielImportCommand.
- Refactored ClaimSetsController FileImport and FileExport actions to use the refactored import model and  new InputFileExtensions methods. Refactored ClaimSetFileIMportModel to …
> [AA-1091] - Phase out direct usage of HttpPostedFileBase in the Management project

- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/packages.config
- Upgraded FluentValidation to 8.6.3 for the Web and Management.Tests projects. All the changes in this commit are automatically added by NuGet.
- Upgraded FluentValidation.Mvc5 to 8.6.1 for the Web project. The FuentValidation.ValidatorAttribute package was automatically upgraded to 8.6.1. All the changes in this commit are automatically added by NuGet.
- Smoke tested forms after the upgrade
> [AA-1097] - Upgrade FluentValidation as high as cross-targeting allows

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Queries/GetResourceClaimsQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetResourceClaimsQuery.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/LocalFileBasedGetCloudOdsHostedComponentsQuery.cs
- Application/EdFi.Ods.AdminApp.Management/OdsSecretConfigurationProvider.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ResourceClaimSelectListBuilder.cs
- Refactored to use Newtonsoft.Json instead of System.Web.Helpers.Json. Used JsonConvert.DeserializeObject and JsonConvert.SerializeObject instead of Json.Encode and Decode.
- Refactored to use the MicrosoftDateFormat in JsonSerializerSettings's DateFormatHandling setting to maintain compatibility with System.Web.Helpers.Json.
- Removed the now unused System.Web.Helpers using directives.
- Moved GetSelectListForResourceClaims() method from GetResourceClaimsQuery to the Web project within a new class ResourceClaimSelectListBuilder. Refactored the GetSelectListForResourceClaims to expect a list argument for all resource claims. Removed the now unused using directive for System.Web.Mvc from GetResourceClaimsQuery.
- Refactored the EditClaimSet action to use the newly moved …
> [AA-1089] - Phase out the Management project's dependency on Microsoft.AspNet.Mvc

- Application/EdFi.Ods.AdminApp.Web/ActionFilters/HandleAjaxErrorAttribute.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
Set TrySkipIisCustomErrors = true for AJAX failues, so that the intended JSON body is not hidden by IIS. Note that we do this already in JsonValidationFilter and SetupController, and the base HandleErrorAttribute also does so.
> [AA-1065] Preserve intended JSON body on failing requests.

- Application/EdFi.Ods.AdminApp.Management.Tests/App.config
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Web.base.config
- Application/EdFi.Ods.AdminApp.Web/packages.config
Here we upgrade platform dependencies to prerelease packages capable of working for both net48 and netcoreapp3.1. A separate ticket will cover upgrading to the final 5.1.0 packages which will only work for .NET Core. This lets us progressively make each project in Admin App work for .NET Core one at a time in upcoming tickets.
Each commit message indicates which package was explicitly upgraded solution-wide. All changes in those commits were caused by the NuGet UI for transitive dependencies.
Developer testing included running the tests locally, interacting with instance setup, Applications, Descriptors, Education Organizations, Users, Claim Sets.
> [AA-1103] upgrade platform dependencies

- Application/EdFi.Ods.AdminApp.Management.OnPrem.Tests/EdFi.Ods.AdminApp.Management.OnPrem.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.OnPrem.Tests/OnPremOdsDatabaseNameProviderTests/WhenGettingDatabaseName.cs
- Application/EdFi.Ods.AdminApp.Management.OnPrem/EdFi.Ods.AdminApp.Management.OnPrem.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Management.UnitTests/EdFi.Ods.AdminApp.Management.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management/Database/AdminAppIdentityDbContext.cs
- Application/EdFi.Ods.AdminApp.Management/Database/AdminAppIdentityDbContext.net48.cs
- Application/EdFi.Ods.AdminApp.Management/Database/EntityFramework6DatabaseModelBuilderExtensions.cs
- Application/EdFi.Ods.AdminApp.Management/Database/EntityFrameworkCoreDatabaseModelBuilderExtensions.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Models/AdminAppUser.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Models/AspNetIdentityShimTypes.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/Identity/RegisterCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/AddUserCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/DeleteUserCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/EditUserCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/EditUserRoleCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/GetRoleForUserQuery.cs
- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/packages.config
- build.ps1
This may be easiest to review commit-by-commit. Note that this resolves AA-1090 as well as AA-803 and AA-1094 since the primary task here immediately allowed for multiple projects to cross-target netcoreapp3.1.
End to end setup of Identity in the ASPNET Core application is a separate ticket. This merely sets us up for that and unblocks other work by making the Management project's usages of Identity cross-target with a successful build.
> [AA-1090] Enable the Management project to cross-compile ASP.NET Identity usages

- Application/EdFi.Ods.AdminApp.Management/Helpers/ConfigurationHelper.cs
- Application/EdFi.Ods.AdminApp.Web.Core/Controllers/HomeController.cs
- Application/EdFi.Ods.AdminApp.Web.Core/Properties/launchSettings.json
- Application/EdFi.Ods.AdminApp.Web.Core/Startup.cs
- Application/EdFi.Ods.AdminApp.Web.Core/appsettings.OnPremisesRelease.json
- Application/EdFi.Ods.AdminApp.Web.Core/appsettings.OnPremisesYearSpecificRelease.json
- Application/EdFi.Ods.AdminApp.Web.Core/appsettings.Release.json
- Application/EdFi.Ods.AdminApp.Web.Core/appsettings.json
- Application/EdFi.Ods.AdminApp.Web.Core/log4net/log4net.OnPremisesRelease.config
- Application/EdFi.Ods.AdminApp.Web.Core/log4net/log4net.OnPremisesYearSpecificRelease.config
- Application/EdFi.Ods.AdminApp.Web.Core/log4net/log4net.Release.config
- Application/EdFi.Ods.AdminApp.Web.Core/log4net/log4net.config
- Application/EdFi.Ods.AdminApp.Web/App_Start/StartupBase.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.nuspec
- Application/EdFi.Ods.AdminApp.Web/Web.OnPremYearSpecificRelease.config
- Application/EdFi.Ods.AdminApp.Web/Web.OnPremisesRelease.config
- Application/EdFi.Ods.AdminApp.Web/Web.Release.config
- Application/EdFi.Ods.AdminApp.Web/Web.base.config
- Application/EdFi.Ods.AdminApp.Web/log4net/log4net.OnPremisesRelease.config
- Application/EdFi.Ods.AdminApp.Web/log4net/log4net.OnPremisesYearSpecificRelease.config
- Application/EdFi.Ods.AdminApp.Web/log4net/log4net.Release.config
- Application/EdFi.Ods.AdminApp.Web/log4net/log4net.config
**.Net48 Changes**
- Moved log4net configuration to separate config files under log4net folder for the net48 project. The added xml elements in log4net.OnPremisesRelease.config and log4net.OnPremisesYearSpecificRelease.config are used to emulate the transform behavior in OnPremisesRelease.config and OnPremisesYearSpecificRelease.config files.
- Added Log4NetConfigPath appSetting to set the configuration file path for log4net for different transforms(environments).
- Refactored ConfigureLogging() to configure log4net using the corresponding log4net config path from the appSetting Log4NetConfigPath and the ILoggerRepository argument to make it similar to the log4Net configuration setup in the .net core projects.
**.Net Core Changes**
- Added log4net configuration to separate …
> [AA-809] - Move log4net config out of Web.config and add logging to .Net Core project

- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web.Core/Startup.cs
- Application/EdFi.Ods.AdminApp.Web.Core/wwwroot/Scripts/site-form-handlers.js
- Application/EdFi.Ods.AdminApp.Web.Core/wwwroot/Scripts/site.js
This PR serves to apply the AutoValidateAntiforgeryTokenAttribute globally in the .NET Core Web project. This performs the same function as the ValidateAntiForgeryTokenOnPostActionsFilter in .NET 48 project to prevent CSRF attacks.
- Proving that altough antiforgery tokens are included in forms by default, they are not enforced. Even after an explicit token removal, POSTs are processed in full.
- Added AutoValidateAntiforgeryTokenAttribute globally to validate the AntiForgery token for POST requests.
- Refactored the submitAjax  function in site-form-handler.js to add the RequestVerification token to the specific "RequestVeirficationToken" request header instead of appending it to the serialized form as the server is looking for the particular header for the token.
- …
> Applied the AutoValidateAntiforgeryTokenAttribute for .NET Core project

- Application/EdFi.Ods.AdminApp.Management.Tests/User/UserTestSetup.cs
- Application/EdFi.Ods.AdminApp.Management/Database/AdminAppIdentityDbContext.net48.cs
- Application/EdFi.Ods.AdminApp.Management/User/DeleteUserCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/EditUserRoleCommand.cs
- Application/EdFi.Ods.AdminApp.Management/User/GetRoleForUserQuery.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/User/EditUserRoleModel.cs
Under .NET Core, some usages of dbContext.Set<T>() compile but will fail at runtime due to subtle discrepancies in the data type T versus EFCore's understanding of what the model should be. The solution is to use the strongly typed DbSet properties from the base class. Unfortunately, under the *old* Identity system in NET48, such a property is not always present. Here we work around that by defining it for NET48, and then using it in both NET48 and .NET Core.
Although I tested this, please be sure that your own testing hits each affected usage.
> Strongly typed dbsets

- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web.Core/Views/Shared/_Settings_Production.cshtml
- Application/EdFi.Ods.AdminApp.Web/Display/TabEnumeration/OdsInstanceSettingsTabEnumeration.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstanceSettings/BaseOdsInstanceSettingsModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstanceSettings/OdsInstanceSettingsModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Settings_Production.cshtml
As we approach the work to port ODS Instance Settings tab pages to .NET Core, we see a few obstacles which would push us to do too much all at once with excess developer friction and risk: OdsInstanceSettingsController and the related OdsInstanceSettingsModel needlessly mixes together concerns from many different features, all just so that they can share the tab layout look and feel.
Thankfully we can get ahead of those pains by first enabling us to split up those unrelated concerns. This PR does that prep work and should therefore have zero impact on behavior.
After this PR, each ODS Instance Settings tab conversion to .NET Core will follow a pattern:
1. Introduce a new subclass of OdsInstanceSettingsModel specific to that tab, containing only the properties needed by that tab.
2. Use …
> Enable splitting up OdsInstanceSettingsController

- Application/EdFi.Ods.AdminApp.Management.Core.Tests/EdFi.Ods.AdminApp.Management.Core.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/AdminAppDataTestBase.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetFileImportCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/CopyClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/DeleteClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetApplicationsByClaimSetIdQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetAuthStrategiesByApplicationNameQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetClaimSetsByApplicationNameQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetResourcesByClaimSetIdQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/SecurityDataTestBase.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/SharingModel.cs
- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web.Core/Views/ClaimSets/_AuthStrategiesModal.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/ClaimSets/_EditClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/ClaimSets/_ExportClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/ClaimSets/_ExportClaimSetPreview.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/ClaimSets/_ResourceEditor.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/wwwroot/Scripts/resource-editor.js
- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/InputFileExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ResourceClaimSelectListBuilder.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetFileImportModel.cs
**.NET Core Web project**
- Included ClaimSetsController, ResourceClaimSelectListBuilder and ClaimSetFileImportModel in the .NET Core project. Included the claimset related views in the .NET Core project.
- Using Newton.Json on the claimset views instead of System.Web.Mvc and refactored to use JsonConvert.SerializeObject instead of Json.Encode with the StringEscapeHandling setting set to escape HTML in order to avoid security issues.
- Refactored to remove the Scripts.Render sections and include the bundled scripts using the script tag.
- Refactored to use a Stream object as an argument instead of the HttpPostedFileBase object.Moved the Serialization and Deserialization of Sharing Model from InputFileExtensions to SharingModel to as it is no longer dependent on the methods …
> [AA-1110] - Finalize Global\Claimsets tab for .NET Core

- Application/EdFi.Ods.AdminApp.Web/Helpers/ApplicationExtensions.cs
Add condition to IsSystemReservedApplicationName method in Application Extension file to do not take null values.
It Fixes Adding and Editing an Application.
> AA-1108 Fix error saving application without application name

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Queries/Ods/OdsDataTestBase.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Ods/DatabaseConnectionProvider.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Ods/Reports/ReportsConfig.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Ods/Reports/UpgradeEngineFactory.cs
- Application/EdFi.Ods.AdminApp.Web.Core/ActionFilters/InstanceContextFilter.cs
- Refactored UpgradeEngineFactory to use the DatabaseEngine appsetting instead of DatabaseProviderHelper for the .NET Core builds.
- Refactored DatabaseConnectionProvider to use the DatabaseEngine appsetting instead of DatabaseProviderHelper for the .NET Core builds.
- Refactored ReportsConfigProvider to use the DatabaseEngine appsetting instead of DatabaseProviderHelper for the .NET Core builds.
> [AA-1151] - Phase out DatabaseProviderHelper usages on .NET Core builds

- Application/EdFi.Ods.AdminApp.Web.Core/ActionFilters/HandleAjaxErrorAttribute.cs
- Application/EdFi.Ods.AdminApp.Web.Core/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web.Core/Startup.cs
- Application/EdFi.Ods.AdminApp.Web.Core/Views/Home/PostSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/Setup/FirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/Setup/PostUpdateSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/wwwroot/Scripts/site.js
- Application/EdFi.Ods.AdminApp.Web/Controllers/HomeController.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Scripts/site.js
- Application/EdFi.Ods.AdminApp.Web/Views/Home/PostSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Setup/FirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Setup/PostUpdateSetup.cshtml
- Added the intermediate screen PostSetup.cshtml for .NET Core and .NET48 projects.
- Added PostSetup action to the Home Controller and updated the redirect urls for PostUpdateSetup.cshtml and FirstTimeSetup.cshtml for both .NET 48 and .NET Core projects.
- Added custom error message to ActionAjax Html helper structure to display the "ODS restart" guidance message along with the server error for both .NET48 and .NET Core projects.
- Added .NET Core compatible HandleAjaxErrorAttribute similar to the one in .NET48 project. Registered the HandleAjaxErrorAttribute globally in .NET Core Startup.
> [AA-1144] - First Time Setup Success should direct users to restart ODS

- eng/teamcity-get-package-version.ps1
Now that there is a single package, remove "Core" from the expected name as it is no longer used to distinguish old from new packages.
> Correct the teamcity-get-package-version script to seek the right package name.

- build.ps1
We do so similar to how the ODS needs it to build reliably. In our case, it is to introduce stability around builds in combination with the BundlerMinifier as suggested by Jon Skeet here: https://github.com/madskristensen/BundlerMinifier/issues/365
> The build script sets MSBUILDDISABLENODEREUSE

- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
During experimentation, signalr began failing unexpectedly after this upgrade, and becomes stable when we revert to 8.0.0.
> Revert upgrading HtmlTags from 8.0.0 to 8.1.1 due to apparent instabilities

- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Settings_Production.cshtml
The idea of this Story was to add a little tag over the ODS instances pages with the current version of the ODS/API that the admin app is connected to.
Also it was added a label to the number at the right bottom of the footer to identify that number like Admin App version
I also did a little improvement getting the Admin App version. For that i added the cache approach there to avoid constantly go to server to get the same variable
> [AA-1176] Display ODS / API version number in ODS instance pages of Admin App

- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/AzureTestSettingsProvider.cs
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/GetDatabaseConnectionFromConfigFileTester.cs
- Application/EdFi.Ods.AdminApp.Management.OnPrem/GetOnPremOdsInstanceQuery.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Configuration/Configuration/OdsSecretConfigurationProviderTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/RawSqlConnectionService.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/ConfigurationHelper.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/ConnectionStrings.cs
- Application/EdFi.Ods.AdminApp.Management/Services/EncryptionConfigurationProviderService.cs
- Added GetConnectionStringByName method to the ConnectionStrings class in order to aid in getting the connectionString by database name.
- Refactored GetOnPremOdsInstanceQuery to use the IOptions pattern to access AppSettings and get the AwsCurrentVersion setting value.
- Refactored EncryptionConfigurationProviderService to use the IOptions pattern to access AppSettings and get the OptionalEntropy setting value. Refactored OdsSecretConfigurationProviderTests to provide an IOptions<AppSettings> mock for EncryptionConfigurationProviderService.
- Refactored RawSqlConnectionService to use the IOptions pattern to access ConnectionStrings. Added an azure integration test to test the GetDatabaseConnectionFromConfigFile functionality in RawSqlConnectionService.
- Refactored …
> [AA-1160] - Phase out ConfigurationHelper in favor of IOptions

- eng/run-dbup-migrations.ps1
Remove DbDeployVersion argument from run-dbup-migrations.ps1 script to avoid warnings running the script to generate the admin app tables.
As you can see now in the image below, the script runs without warning messages:
> [AA-1172] Resolve version number warning when running migration script

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- eng/database-manager.psm1
As it was done in run-dbup-migrations powershell script, it was necessary to adjust the version in database-manager script.
The idea was to include a constant at the top of the file and reference it where it was needed instead of put string with different versions over all the script.
> [AA-1172] Adjust version number in database-manage powershell script

- Application/EdFi.Ods.AdminApp.Web/Views/Application/_ApplicationsTable.cshtml
In Current version of the ODS/API  sample profiles were temporarily dropped from v5.1.0 - but coming back in v5.2.0.
For that reason it was defined to Add "None" value to profile field in application list view instead of showing up an empty or blank field.
> [AA 1195] Add "None" value to empty applications profile

- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/AddClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/CopyClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/EditClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_AddClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_CopyClaimSetModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_EditClaimSet.cshtml
What was happening?
When we wanted to add a new claim set or copy from a pre existing one and the claim set name was greater than 255 characters(max allowed in database) a general error related to database was shown to the user.
What is the Fix?
First of all was added a max length restriction in the UI to restrict the user to type a claim set name greater than 255 characters, and for the other side is was added a Fluent validation rule to AddClaimSetsModel, CopyClaimSetModel and EditClaimSetModel classes to prevent going to database instead of user manually edit the html to remove max length validation.
> [AA-1199] Handle error message when claim set name is too big

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/AddClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/CopyClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/EditClaimSetCommandTests.cs
Include tests to Add, Copy and edit claim set actions when name length greater than 255 characters. 
This is the second part of the ticket because the first version did not include the tests.
> [AA-1199] Include tests to Add, Copy and edit claim set actions when name length is too big

- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/BaseGlobalSettingsModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/GlobalSettingsModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/ClaimSetDetails.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/EditClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_ClaimSetDetails.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_EditClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/ClaimSets.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Settings_Global.cshtml
- Added an abstract BaseGlobalSettingsModel. Refactored GlobalSettingsModel to inherit from BaseGlobalSettingsModel. Refactored _Settings_Global.cshtml to use BaseGlobalsettingsModel.
- Added ClaimSetModel to use as the base model for EditClaimSet and ClaimSetDetails views.
- Added EditClaimSet and ClaimSetDetails views to render the _EditClaimSet and _ClaimSetDetails partials. Refactored the views and links on ClaimSets view to not use ajax classes.
- Refactored ClaimSet controller actions ClaimSetDetails and EditClaimSet to use the ClaimSetModel and new views.
- Changed the col sizing on the claimset details adn edit tabs to macth the older version.
> [AA-879] - When opening in a new tab, page loads without styles fix

- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/ClaimSets.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Layout.cshtml
**View Loads Twice issue fix**
- Refactored the EditClaimSet and AddClaimSet actions in the claimet controller to use the new method to get the EditClaimSetmodel from the claimset id. Refactored the AddClaimSet action to return the PartialView for EditClaimSet in order to avoid duplicate views.
**ClaimSet Warning Message disappears fix**
- Moved setting the cacheTimeout variable to the Layout view to avoid removing it on navigating away from the claimsets tab and coming back.
- Moved the claim-set-warning-message div within the claimset listing div to only this div on the claimsets listing view.
> [AA-1203] - Add Claimset Loads view twice and ClaimSet Warning Message disappears

- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/BulkRegisterOdsInstancesModel.cs
A few fields became no longer used in recent updates to the BulkRegisterOdsInstancesModelValidator. This simply resolves the warnings by applying the ReSharper "Remove Unused Field" refactoring for each offender.
AA-1206 is focused on these simple warnings. The last remaining warning as of this commit will be covered by a separate ticket, AA-1215.
> [AA-1206] Apply the ReSharper "Remove Unused Field" refactoring to address compiler warnings

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/BulkUploadController/WhenRunningBulkUpload.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/BulkUploadController.cs
- Refactored the BulkFileUpload action in BulkUploadController to throw an exception instead of NoContent for an empty file. This was done to avoid the ajax request success data for this call to be undefined and result in an "Cannot read property 'authentication_required' of undefined" console error as a result of a call to redirectIfAuthenticationRequired  in site.js
- Refactored the empty file BulkUpload unit test to reflect the changes in the BulkFileUpload action.
> [AA-1225] - Investigate use of "authentication_required" and handle errors related to it

- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/BulkUploadJob.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/LearningStandardsJob.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/ProductionSetupJob.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/WorkflowJob.cs
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/signalr-progress.js
Background: Background jobs like those for Bulk Load and Learning Standards use Hangfire for background job processing, and while jobs make progress they use SignalR to broadcast those progress updates to client browsers. Those SignalR messages amount to progress bar percentage values increasing over time as well as some related state and user-facing label text updates. Prior to Admin App's migration to .NET Core, we naturally used the pre-.NET-Core version of SignalR, and the migration included porting to the modern .NET Core compatible version of SignalR. In that upgrade, SignalR changed its primary mechanism of sending a message to clients: what had been a synchronous call before is now an async call with no synchronous overload. Additionally, our background jobs have historically …
> [AA-1215] await asynchronous job status updates

- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Database.nuspec
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.nuspec
- EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
This repo produces NuGet packages from 3 nuspec files:
* Application\EdFi.Ods.AdminApp.Web\EdFi.Ods.AdminApp.Web.nuspec
* Application\EdFi.Ods.AdminApp.Web\EdFi.Ods.AdminApp.Database.nuspec
* EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
For all three, we ensure that the root folder's authoritative LICENSE and NOTICES.md files get copied into the package, and that license metadata tags are included in the nuspec. The metadata tags allow for package feed tools to display the fact that these packages are released under Apache 2.0.  As an example of how to properly specify that metadata, we imitated the nuspec syntax found in the HtmlTags third party library, which also releases under Apache 2.0 and which displays that correctly at …
> [AA-1063] Add LICENSE, NOTICES, and license metadata to all packages in made by the AdminApp repo

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
- build.ps1
- eng/run-dbup-migrations.ps1
- Use prerelease version of AppCommon with changes to use Azure Artifacts
- Change URLs to use azure artifacts
> [AA-1007] Use azure artifact feed

- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
This prevents ODS version lookup failures from breaking the surrounding page: the version is shown when available, and exceptions are logged, but the page is given the opportunity to otherwise load.
> [AA-1228] Improve user experience when ODS version lookup throws exceptions

- .teamcity/_Self/Project.kt
- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/CloudOdsAdminAppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/ApplicationKeyModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/ApplicationsIndexModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Application/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Application/_ApplicationKeyAndSecretContent.cshtml
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- BuildDockerDevelopment.ps1
- build.ps1
**NOTE: This PR is a companion of the  [Docker counterpart](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker/pull/50)**
- Added ApiExternalUrl appsetting to set the ods/api url. This appsetting is only supposed to be used for displaying the correct url in docker environments.
- Added a private method GetApiUrlForDisplay to replace the production Api Url with the specified ApiExternalUrl if present. Refactored the controller actions to use the method.
- Updated the build script and BuildDockerDevelopment script to take the new appsetting of ApiExternalUrl into account.
> [AA-1239] - Display external API URLs under Docker

- Application/EdFi.Ods.AdminApp.Web/Helpers/ApplicationExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/AddApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/EditApplicationModel.cs
- Removed IsSystemReservedApplicationName extension method because in its current form it is not a truthful check for SystemReservedApplicationName and always returns false for both the sharedinstance mode and multi-instance mode.
- We already have a IsSystemReservedVendor check which is more accurate in determining whether an application with a particular name should be allowed in the database depending on its vendor association.  
- Removed usages of IsSystemReservedApplicationName as well as validation rules depending on it.
> [AA-1183] - Revise validations of CloudOdsAdminApp.ApplicationName

- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
> [TSINSTALL-94] PART-3 Update AppCommon version to 1.3.0 to avoid net 48 pre-requisites checking during installation

- Application/EdFi.Ods.AdminApp.Management.Tests/Helpers/StringExtensionsTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiFacadeTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/DescriptorsController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/StringExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Descriptors/DescriptorCategoriesModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Descriptors/_DescriptorCategories.cshtml
- Refactored GetAllDescriptors to use the "paths" property of the swagger response instead of "definitions". Returned the complete descriptor path instead of category names from the function.
- Added GetDescriptorCategoryName, GetDescriptorCategoryIdentifier, CapitalizeFirstLetter, DescriptorPathParts to StringExtensions. These extension methods are used to get the appropriate descriptor category name and category id from the descriptor path.
- Used GetDescriptorCategoryName and GetDescriptorCategoryIdentifier to refactor the view html to use category name only for the display, category id for the div panel expansion logic and the complete category route as the action parameter.
- Refactored GetDescriptorsByName to use the updated descriptorPath parameter.Renamed …
> [AA-1137] - Descriptors page - Load all descriptors regardless of namespace

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/RegenerateApiClientSecretCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/RegenerateApiClientSecretCommand.cs
When a key and secret is used against the ODS, the ODS ensures that it is hashed and marks it as hashed. When Admin App regenerates a secret, it *should* also reset the corresponding SecretIsHashed flag so that the ApiClient object state is accurate. Otherwise, if a user creates a key and secret, uses it, and then regenerates the secret in Admin App, the new secret is not in fact usable. Users no longer have to create a whole new Application as a workaround.
I detected and fixed this against an example 5.0.1 ODS. The implementation of the ODS side behavior understandably moved during the .NET Core work for 5.1.0, so QA will still need to verify against that as a noteworthy case for completeness, but the fix is expected to work there as well.
> [AA-1136] fix regeneration of used secrets

- docs/developer.md
Improve developer-facing guidance on getting a new local Admin App development environment up and running such that all integration tests can be expected to pass.
* Fixes mentions of the migration script so they consistently refer to its true location in the eng folder.
* Suggests running the build script in 'buildandtest' mode to verify the setup.
* Having migrations and a successful run of the tests ensures that subsequent Test Explorer runs complete successfully without further intervention, just like in the build server.
> [AA-1174] Improve developer-facing guidance for setting up locally

- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Application/EdFi.Ods.AdminApp.Web/UserMustExistHandler.cs
Using MVC Core Authorization Policies, ensure that users are authorized if they are both authenticated (a valid login cookie exists) *and* a corresponding User record still exists for that user.
This gives a consistent experience for two interesting cases:
* A developer logs in, and while the cookie is still considered valid the developer resets the contents of their Users table. The cookie is still considered valid for Authentication but here we apply more strict Authorization and send them to the Login page again.
* A user logs in, and while they are interacting with the site a Super Admin deletes their account. As the first user tries to continue interacting, they are rightly sent back to the Login page.
Useful links which led to this solution:
* …
> [AA-932] A user must be both logged in and have a matching Users record to access protected pages.

- Application/EdFi.Ods.AdminApp.Management.Tests/Services/ConnectionStringServiceTests.cs
- Application/EdFi.Ods.AdminApp.Management/Services/ConnectionStringService.cs
- Application/EdFi.Ods.AdminApp.Web/appsettings.Docker-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-SharedInstance.json
- BuildDockerDevelopment.ps1
- build.ps1
- docs/developer.md
This generalizes connection string `"{0}"` replacement patterns so that, just like the ODS implementation itself, we too allow for token replacement for *all* supported API modes, not just the multi-instance modes.
Specifically, just like the ODS, we now support a connection string for Shared Instance mode with the template database name `"EdFi_{0}"` which naturally gets substituted to `"EdFi_Ods"`. The primary effect is that our various sample appsettings files become that much more alike. The ability to use some alternate specific database name is unharmed, which for example happens in Cloud ODS deployments.
I began with characterization test coverage of the affected ConnectionStringService and then extended the tests as the handling of Shared Instance evolved.
This also includes an …
> AA-1182 generalize connection string token replacement to match ODS token replacement

- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/ClaimSets.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site.js
Rephrased the claim set editor's ODS restart suggestions to be environment-agnostic by using "restart the ODS/API" instead of "reset IIS". This also matches the restart suggestion on first time setup.
> [AA-1251] - Improve phrasing of the claim set editor's ODS restart suggestions to be environment-agnostic

- Application/EdFi.Ods.AdminApp.Web/Controllers/ClaimSetsController.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_ImportClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/ClaimSets.cshtml
- Renamed ImportExportClaimset to ImportClaimset view. Refactored to remove mentions of export and removed the "Export Claimsets" button on the ImportClaimSet view.
- Added Export Claim Set button to the Claimsets view. Renamed ExportClaimSetIndex to ExportClaimset.
> [AA-1201] - Separate claimset import and export to remove additional screen

- Application/EdFi.Ods.AdminApp.Web/Controllers/SchoolYearsController.cs
Added the [BypassInstanceContextFilter] attribute to the SchoolYearsController to avoid the check for instance context as it is not needed to edit the school year. The modal is informed about the instance using the instance listing.
> [AA-1280] - Issue opening the School Year Edit modal with no current instance known

- .teamcity/Web/templates/BuildAndTestTemplate.kt
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- build.ps1
- Removed the production GA property measurement ID from appsettings.json as the value is now shifted to TeamCity.
- Added PopulateGoogleAnalyticsAppSettings command to the build script to update appsettings.json with the GoogleAnalyticsMeasurementId value provided. Refactored build script to take in a GoogleAnalyticsMeasurementId parameter for this command.
- Added a build step to the BuildAndTest template to populate the GA measurement ID before proceeding to create the nuget package.
> [AA-1288] - Move Production GA property Measurement ID to TeamCity

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/AutoMapper/AdminWebMappingProfile.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/EditPostSecondaryInstitutionModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_DeleteOrganizationModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_EditPostSecondaryInstitutionModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_PostSecondaryInstitutions.cshtml
**NOTE - This should be merged in after [*181 PR*](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/181) has been merged to AA-1315**  
- Added EditPostSecondaryInstitutionModel. Added mappings for EditPostSecondaryInstitutionModel.Added EditPostSecondaryInstitution actions. Added unit tests for EditPostSecondaryInstitution.Added EditPostSecondaryInstitutionModal view. Refactored to use EditPostSecondaryInstitution action in PostSecondaryInstitutions.
- Added DeletePostSecondaryInstitution action. Added unit tests for DeletePostSecondaryInstitution.Refactored _DeleteOrganizationModal view to take PostSecondaryInstitution into account.
> [AA-1315] - Edit and Delete PostSecondaryInstitution implementation

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/AutoMapper/AdminWebMappingProfile.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/EditPsiSchoolModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/EditSchoolModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_AddPsiSchoolModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_EditPsiSchoolModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_PostSecondaryInstitutions.cshtml
**NOTE: This should be merged in after [*182 PR*](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/182) has been merged to AA-1315**
- Refactored EditSchoolModel to use the existing school properties via inheritance. 
Added EditPsiSchoolModel. Added mappings for EditPsiSchoolModel. PsiSchools.
- Added GetPsiSchoolById and EditPsiSchool api actions to OdsApiFacade.Added actions for editing Psi Schools in EducationOrganizationController. Added unit tests for EducationOrganizationController EditPsiSchool flow.Added_EditPsiSchoolModal view for the edit psi school flow.
- Refactored to use the existing class for Delete PSI School flow avoiding duplication of the existing Delete School flow.
> [AA-1315] - Edit and Delete PostSecondaryInstitution School implementation

- .teamcity/_Self/Project.kt
**NOTE: This PR should be merged only after the 2.2.1 release artifacts have been accepted. Also, the build-counters and installer version parameters on TeamCity need to be checked for the correct state before merging this PR**
Admin App version bump to 2.3.0 after 2.2.1 release
> Admin App version bump to 2.3.0 after 2.2.1 release

- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddLocalEducationAgencyModelTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddPostSecondaryInstitutionModelTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddPsiSchoolModelTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddSchoolModelTests.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddLocalEducationAgencyModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddPostSecondaryInstitutionModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddPsiSchoolModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddSchoolModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/EducationOrganizationValidationHelper.cs
Although they appear to be supported and have behaved in practice, async operations within FluentValidation rules are considered a deadlock risk according to FluentValidation's maintainer.
Fortunately, only a small number of our rules ever performed work with async Task objects, all related to Education Organization ID uniqueness checks.
This PR complies with the guidance of having no async work within FluentValidation rules by moving that rule check into the related controller actions where async is naturally intended/supported. By crafting the same ModelState-based 400 response as would have been returned by JsonValidationFilter, the preexisting javascript which displays validation errors picks up on it unaware of the code change on the server side, giving the user a consistent …
> [AA-1262] Phase out async FluentValidation rules

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiFacadeTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Added GetSchoolsByParentedOrgId to OdsRestClient to fetch schools using the leaId filter
- Added GetSchoolsByLeaIds to OdsApiFacade to fetch schools based on the list of leaIds provided.
- Refactored LocalEducationAgencyList to fetch schools based on the Leas on the page.
- Refactored and added unit tests corresponding to the GetSchoolsByLeaIds flow.
> [AA-1281] - Improve Ed Orgs paging performance by fetching minimal Schools

- Application/EdFi.Ods.AdminApp.Management.Azure/CompleteAzureFirstTimeSetupCommand.cs
- Application/EdFi.Ods.AdminApp.Management.OnPrem/CompleteOnPremFirstTimeSetupCommand.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetCheckServiceTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Setup/CompleteOdsFirstTimeSetupCommandTester.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/ClaimSetCheckService.cs
- Application/EdFi.Ods.AdminApp.Management/ICompleteOdsFirstTimeSetupCommand.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/HomeController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ProductImprovementController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/SetupController.cs
- Application/EdFi.Ods.AdminApp.Web/_Installers/CommonConfigurationInstaller.cs
- Added ClaimSetCheckService with the isRestartRequired method to check if the required claimsets exist in the database. Registered the ClaimSetCheckService.
- Refactored the controllers to add the check for required claimsets and display the Restart ODS screen based on the check.
- Added ClaimSetCheckService unit tests for the ClaimSetCheckService.
> [AA-1327] - Show ODS restart screen based on Claimset check

- build.ps1
- Added Run action to the build script. Added LaunchProfiule parameter to go along with Run action in order to specify the launch profile for Admin App.
- Added NewDevCertificate to create a new dev certificate if it does not already exists to allow the HTTPS endpoint configuration.
> [AA-1207] - Add run action in build script for Admin App

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetFileImportCommandTests.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetFileImportModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_ImportClaimSet.cshtml
Added file extension check for the ImportFile property in ClaimSetFileImportModel. Added corresponding unit test for the new check.
> [AA-1235] - Fixed error message when importing non JSON file while importing ClaimSets

- .gitignore
- EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/build-package.ps1
- EdFi.Suite3.Installer.AdminApp/nuget-helper.psm1
- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
- EdFi.Suite3.Installer.AdminApp/test.ps1
**NOTE: This PR should be merged only after the release of the AppCommon package from the [*ODS-4811 Ed-Fi-ODS-Deploy repo PR*](https://github.com/Ed-Fi-Alliance/Ed-Fi-ODS-Deploy/pull/215) and the AppCommon package version has been updated with the release version in this repo**
- Refactored prep-installer-package.ps1 to use the latest AppCommon package and made changes to the folder structure for the new package. Removed references to the Ed-Fi repos and use the added nuget-helper module to get the AppCommon nuget package.
- Refactored the Import-Module statements to use the scripts under AppCommon folder. Removed references to the path-resolver scripts as they are no longer needed.
- Updated the nuspec and gitignore files based on the AppCommon changes.
- Refactored …
> [ODS-4811] - Refactoring admin app installer to consume the new app common package changes

- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
Bump RestSharp from 106.11.5 to 106.12.0 in EdFi.Ods.AdminApp.Management.
> Upgrade RestSharp to latest version

- Application/EdFi.Ods.AdminApp.Management.Tests/Infrastructure/ProductRegistrationModelTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/GetOdsInstanceRegistrationsQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Management/Instances/GetOdsInstanceRegistrationsQuery.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/IdentityController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ProductImprovementController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ProductRegistration.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ProductRegistrationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Properties/launchSettings.json
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Application/EdFi.Ods.AdminApp.Web/_Installers/CommonConfigurationInstaller.cs
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
1. The ProductRegistrationModel presents a reliably-serializable set of telemetry fields.
2. New AppSetting ProductRegistrationUrl, initially blank for now while that service is being developed.
3. In local development environments, product registration notifications are configured to hit a diagnostic endpoint hosted within Admin App instead of the external public production endpoint. The diagnostic endpoint does not exist during production runs.
4. The ProductRegistration class POSTs a ProductRegistrationModel to the configured ProductRegistrationUrl, if and only if the admin has opted into Product Improvement with a Product Registration Id and the configured ProductRegistrationUrl is populated in AppSettings.
5. We attempt product registration upon every successful login, except for the …
> [AA-1342] send product registration analytics

- Application/EdFi.Ods.AdminApp.Web/Controllers/SetupController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/OdsApiFacadeExtensions.cs
- docs/developer.md
- Removed WarmupApiServer() method and associated usages/code to avoid misleadingly logging "API stored key and secret have been corrupted" issue. This doesn't really make sense as we already indicate the user to restart the ODS/API anyway
- Updated the dev readme to add build.ps1 Run action documentation.
> [AA-1237] - Removed misleading API warmup exception logged during first time setup flow

- Application/EdFi.Ods.AdminApp.Management/Api/TokenRetriever.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site.js
This PR introduces additional exception and response handling to the `TokenRetriever` in an effort to provide more specific messages for given scenarios and additional context within those messages.
- adds new handling and specific messages for `404`, `503`, and empty (`0`) responses
- adds handling and message for non-JSON response
- re-emphasizes error display to put focus on specific message before general handling recommendation
> [AA-1351] Improve error message when unable to reach the ODS API

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/uninstall.ps1
- Added Invoke-ResetIIS function to prompt the user to choose whether to reset IIS or not.
- Refactored Uninstall-EdFiOdsAdminApp to move out the Uninstall-EdFiApplicationFromIIS call to a separate function in order to allow Invoke-ResetIIS to be called separately from the uninstall flow. Added calls to Invoke-ResetIIS for both update and uninstall flows.
- Added an uninstall.ps1 script.
> [AA-1371] - Prompt and restart IIS from powershell when upgrading and uninstalling

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
Adds a new check in the Upgrade script to verify the specified upgrade version is newer than the existing install.
In addition:
- adds helper function for version checking
- update other compatibility check to use it as well
- minor readability refactors (favor early exit over `if/else`
> [AA-1361] Show Error Message on Upgrade Script When Version Specified Is Same or Previous

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
Restores support for checking and comparing `-pre####` versions when using the Upgrade installer script.
Version number is extracted from the `-` tag and appended to the rest of the build number.
For example `2.0.1-pre003` is treated as `2.0.1.003` during version comparison (leading zeros are ignored by default as well)
Supports exhaustive multi-part or multi-tag versions if necessary: `2.0.1-pre003.2-build004` becomes `2.0.1.003.2.004`, though such a versioning scheme would not be recommended for actual use.
> [AA-1386] Upgrade script is not working with newer 'pre' versions

- eng/package-manager.psm1
Update the TLS configuration before fetching the nuget.exe from the web to ensure the download executes correctly regardless of server config.
To test:
- Remove nuget from PATH environment variable (if you have one)
- Delete `eng\.tools\nuget.exe`
- Run default `build.ps1`
Build should fetch `nuget.exe` and continue executing successfully.
> [EDFI-991] Missing TLS Configuration During Build

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
- EdFi.Suite3.Installer.AdminApp/uninstall.ps1
@pmcvtm @saa14 
1. Removed WebApplicationDirectory, since it was confusing to have both WebApplicationname and WebApplicationDirectory. 
If user wants to provide custom name for AdminApp application, it can be provided with WebApplicationname  parameter. Internally the WebApplication path will be generated by combining Websitepath and WebApplicationname
2. Actual error (AA-1380) cannot be reproduced, since user doesn't have option to provide two different values for WebApplicationname and WebApplicationDirectory as before.
3. Testing: General testing on install, upgrade and uninstall flows. For testing with custom values Install-WithCustomSettings, Upgrade-ApplicationWithCustomSettings scenarios from .\test.ps1 can be used.
Thanks
> [AA-1380] Admin App Installer issue on re-installation 

- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiFacadeTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiResult.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
Fix the ODS API client `Delete` handler to check if the response is a success and set the error message appropriately (instead of just on exception).
Included default message as well as potentially a Content message. Other client methods are correctly checking this and changing the status accordingly.
This _does not_ adjust the delete JavaScript handling to wire into the new error page handling, so it still shows a toast.
> [AA-1392] Success Message When Delete Fails

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/AddVendorCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/EditVendorCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/AddVendorCommand.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/EditVendorCommand.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/StringExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/AutoMapper/AdminWebMappingProfile.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/AddVendorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/EditVendorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/VendorOverviewModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/_AddVendorModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/_EditVendorForm.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/_VendorsTable.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Content/css/Site.css
- Renamed NamespacePrefix fields to NamespacePrefixes to correctly denote the multiple namespace prefixes.
- Refactored EditVendor and VendorOverview mappings to expect a comma-separated list of multiple namespace prefixes. Added a string extension method to create a string by joining an input list of strings using a delimiter.
- Added an HtmlHelperExtension for a textarea input block. Replaced the input blocks on AddVendor and EditVendor screens with the textarea input block. Added the add namespace prefix input-group to AddVendor and EditVendor screens. Added help text to the form inputs.
- Added javascript logic to handle the interactions between the textarea input and add namespace prefix input group to the AddVendor and EditVendor screens.
- Refactored the …
> [AA-893] - Add support for multiple namespace prefixes for a vendor

- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiFacadeTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
Fixes ODS API Client to treat the `204 No Content` response from some DELETE requests as Success (instead of Failure since it's `!= 200 OK`)
- changes response "success" criteria to use `IsSuccessful` instead of checking specific status codes
- fixes to parse error message from `Content` or use default when response has no `ErrorMessage`
- refactor methods to unify coupled request/response/handling methods
- does _not_ change to use Global Error Handler
- failures still return a `OdsApiResult` instead of throwing an exception to be handled by middleware
> [AA-1392] Follow-Up: Overzealous API Failure Responses

- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/HealthCheckServiceExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Added AspNetCoreHealthCheck packages to perform the database probes needed for Postgres and SQLServer admin database during the docker healthcheck.
- Added HealthCheckServiceExtensions class to add the database health check depending on the database engine being used. Added IsSqlServer method to Startup to check for the database engine and refactored using Staertup.cs using this check. Called MapHealthChecks on the endpoint builder with the health check endpoint.
> [AA-1358] - Add support for Docker Health checks

- .github/workflows/e2e.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/cucumber.js
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
**This should be merged after https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/248 is merged**
Run playwright tests against the ODS instance created.
- The purpose of these task is not for the tests to pass, just to run. The new tests will be added in a future ticket.
- The results are currently not saved since this will be covered in a future ticket.
Needs https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Docker/pull/102 to be merged to fix issue with case of folder names
> [ODST-194] Run playwright tests in action

- .github/workflows/e2e.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/.gitignore
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/functions.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/teardown.ts
- Using playwright traces rather than videos and screenshots for troubleshooting.
- Results can be executed from the command line or uploaded to https://trace.playwright.dev/
- Uploading traces when there's a failure executing the tests in GitHub Action
> Use playwright traces

- .github/workflows/build.yml
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure.UnitTests/EdFi.Ods.AdminApp.Management.Azure.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure/EdFi.Ods.AdminApp.Management.Azure.csproj
- Application/EdFi.Ods.AdminApp.Management.OnPrem/EdFi.Ods.AdminApp.Management.OnPrem.csproj
- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Automapper/AdminManagementMappingProfileTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/EdFi.Ods.AdminApp.Management.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management/Database/EntityFrameworkCoreDatabaseModelBuilderExtensions.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/GetOdsStatusQuery.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Helpers/InputFileHelper.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ValidationExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/AddApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/EditApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Home/ErrorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/BulkRegisterOdsInstancesModel.cs
- EdFi.Suite3.Installer.AdminApp/global.json
- build.ps1
- docs/developer.md
**Upgrades/Migration**
- Updated the target framework to netstandard 2.1 for the Management projects.
- Updated the target framework to net6.0 for Azure.IntegrationTests and Management.Tests projects since they have a dependency on AdminApp.Web project.
- Updated the target framework to net6.0 for the EdFi.Ods.AdminApp.Web project.
- Upgraded nuget packages on AdminApp.Web to the versions compatible with net6.0.
- Upgraded nuget packages on AdminApp.Management to the versions compatible with netstandard2.1.Upgraded NUnit nuget packages on the Management projects to the versions compatible with net6.0/netstandard2.1.
- Updated global.json sdk version to net6.0.
- Updated github action workflow to use .net 6.0.x instead of .net core 3.1.x.Updated developer docs to refer to …
> [AA-1423] - Upgrade to dotnet 6

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetFileImportCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/ClaimSetFileImportCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/Extensions/AuthorizationStrategiesExtension.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetResourcesByClaimSetIdQuery.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_AuthStrategiesModal.cshtml
@pmcvtm 
Please help review and merge changes.
The code changes are similar to AA-1506. Modified test methods on creating/ setting up the Claim set resource claims, since the existing (old) ResourceClaims table accepts duplicates. 
Thanks,
> [AA-1517] claim set import not retaining the authorization strategy overrides

- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.csproj
- Application/EdFi.Ods.Admin.Api/Features/Connect/ConnectController.cs
- Application/EdFi.Ods.Admin.Api/Features/Connect/RegisterService.cs
- Application/EdFi.Ods.Admin.Api/Features/Connect/TokenService.cs
- Application/EdFi.Ods.Admin.Api/Features/Vendors/VendorFeatures.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/AdminApiDbContext.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityConstants.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityModels.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/TokenEndpointBodyDescriptionFilter.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Program.cs
- Application/EdFi.Ods.Admin.Api/Properties/launchSettings.json
- Application/EdFi.Ods.Admin.Api/appsettings.Development.json
- Application/EdFi.Ods.Admin.Api/appsettings.json
- Application/EdFi.Ods.AdminApp.Web/Artifacts/MsSql/Structure/Admin/202205080900-CreateAdminApiSchema.sql
- Application/EdFi.Ods.AdminApp.Web/Artifacts/MsSql/Structure/Admin/202205090900-AddApiAuthTables.sql
- Application/EdFi.Ods.AdminApp.Web/Artifacts/PgSql/Structure/Admin/202205080900-CreateAdminApiSchema.sql
- Application/EdFi.Ods.AdminApp.Web/Artifacts/PgSql/Structure/Admin/202205090900-AddApiAuthTables.sql
Introduce authentication and authorization to Admin API using the [OpenIddict](https://documentation.openiddict.com/index.html) library.
- follows "client credential" flow to serve auth tokens for use by other applications
- supports a single "full access" scope that is granted and required on all endpoints
- registration is disabled by default in prod, but overridden when no Applications are registered
- when testing, you can [disable token encryption](https://documentation.openiddict.com/configuration/token-formats.html#disabling-jwt-access-token-encryption) to validate contents in service such as [jwt.io](https://jwt.io/)
**Remarks**
- OpenIddict endpoints do not return responses in the same format as the rest of AdminAPI, which can be expected as it's its own 'server' context
- …
> [AA-1462] Admin API Authentication

- .github/workflows/e2e.yml
- .github/workflows/publish.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/firstTimeSetup.feature
Updating retention days for artifacts.
E2E Artifacts:
Artifacts from test results and test error logs are saved for 10 days.
Artifact for NuGet packages are saved for 30 days.
> [AA-1542] Updating artifact retention dates

- .github/workflows/e2e-reports.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/ARCHITECTURE.md
- Application/EdFi.Ods.AdminApp.E2E.Tests/README.md
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/modelResolver.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/reports/reports.md
- Adding instructions to execute the tests.
- Adding diagrams to represent the structure of the tests.
- Adding instructions to send results to Zephyr
- Fixing branch verification when sending reports to Zephyr
> [AA-1530] Adding documentation for E2E Tests

- .github/workflows/promote-release.yml
- .github/workflows/publish-installer.yml
- .github/workflows/publish.yml
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
- EdFi.Suite3.Installer.AdminApp/build-package.ps1
- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
- build.ps1
- Create new action to build Admin App installer.
- Add build steps for Admin App Web and Database.
- Including Installer into packages to be promoted to release
- Updating ps script to not depend on globally installed NuGet (matching configuration for Data Import)
> [AA-1535] Migrate Admin App Web, Database and Installer builds from TeamCity

- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/Features/Connect/ConnectController.cs
- Application/EdFi.Ods.Admin.Api/Features/Connect/RegisterService.cs
- Application/EdFi.Ods.Admin.Api/Properties/launchSettings.json
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/RegenerateApiClientSecretCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/RegenerateApiClientSecretCommand.cs
Update Admin API Postman Collection to include tests for `/applications` endpoints + expand `/vendors` tests to match new patterns and increase coverage. Besides test coverage, the main goal here is to allow future endpoints to follow the request pattern and copy scripts in a similar manner, to make writing them easier.
- adds requests / assertions per-response (OK, Bad Request, Not Found)
- asserts against response result values for accuracy
- includes fixes to API where tests failed
- correct 404 response from `/applications/reset-credentials`
- format of `/connect/register`
**Testing**
- make sure you're running in "Production" mode for error handling
- added a new launch profile for VS
- manually you can set `ASPNETCORE_ENVIRONMENT`, but other settings need to be updated as well
- …
> [AA-1548] Admin API E2E Test Expansion

- .gitignore
- Application/EdFi.Ods.Admin.Api/Compose/pgsql/compose-build.yml
- Application/EdFi.Ods.Admin.Api/Compose/pgsql/env.example
- Application/EdFi.Ods.Admin.Api/Docker/mssql/appsettings.template.json
- Application/EdFi.Ods.Admin.Api/Docker/mssql/env.example
- Application/EdFi.Ods.Admin.Api/Docker/mssql/log4net.config
- Application/EdFi.Ods.Admin.Api/Docker/mssql/run.sh
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/appsettings.template.json
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/env.example
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/log4net.config
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/run.sh
- Application/EdFi.Ods.Admin.Api/Docker/ssl/generate-certificate.sh
- Application/EdFi.Ods.Admin.Api/Docker/ssl/openssl.config
- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.nuspec
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityExtensions.cs
- Application/EdFi.Ods.Admin.Api/Program.cs
- Application/EdFi.Ods.Admin.Api/appsettings.json
- Application/EdFi.Ods.Admin.Api/mssql.Dockerfile
- Application/EdFi.Ods.Admin.Api/pgsql.Dockerfile
- BuildAdminApiDockerDevelopment.ps1
- BuildDockerDevelopment.ps1
- build.ps1
- Added 'Authority' authentication appsetting. This is to allow different configurations for IssuerUrl and Authority appsettings for authentication.
- Added Docker configuration files and script for Admin Api container against SQL Server.
- Added Docker configuration files and script for Admin Api container against Postgres.
- Added generate-certificate.sh to create self-signed SSL certificates which can be used when testing the containers.
- Added docker compose file and corresponding env.example for Postgres flow.
- Added AdminApi relatted container functions for testing in build.ps1. Renamed AdminApp related container functions to avoid confusion. Added BuildAdminApiDockerDevelopment.ps1 to facilitate quick dev testing inside AdminApi docker container.
> [AA-1469] - Docker Deployment For AdminApi

- Application/EdFi.Ods.Admin.Api/ActionFilters/OperationResponsesDocumentFilter.cs
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/Features/Connect/RegisterService.cs
- Application/EdFi.Ods.Admin.Api/Features/Connect/TokenService.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityConstants.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/TokenEndpointBodyDescriptionFilter.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Properties/launchSettings.json
Future-proof the Admin API authentication endpoint (`/connect/token`) by including desired scopes in the request. This will allow us to introduce new scopes and issue tokens which only contain some of them without making changes to that endpoint's shape.
- no change in token contents / security requirement
- reading and setting requested scopes added to token service
- when token is not granted the required scope, .NET returns a 403 Forbidden
- swagger updated to list valid scopes + include in documentation for `connect/token` endpoint
- E2E tests updated to both include scope in token requests + cover test for requesting invalid scope
- manually tested requesting a scope which a client does not have access to, which is blocked by both OpenIddict validation + explicitly in `TokenService` …
> [AA-1549] Include Scope in API Auth Requests

- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.csproj
- Application/EdFi.Ods.Admin.Api/Features/Applications/AddApplication.cs
- Application/EdFi.Ods.Admin.Api/Features/Applications/DeleteApplication.cs
- Application/EdFi.Ods.Admin.Api/Features/Applications/EditApplication.cs
- Application/EdFi.Ods.Admin.Api/Features/Applications/ReadApplication.cs
- Application/EdFi.Ods.Admin.Api/Features/Applications/ReadApplicationsByVendor.cs
- Application/EdFi.Ods.Admin.Api/Features/Applications/ResetApplicationCredentials.cs
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/ReadClaimSets.cs
- Application/EdFi.Ods.Admin.Api/Features/Vendors/AddVendor.cs
- Application/EdFi.Ods.Admin.Api/Features/Vendors/DeleteVendor.cs
- Application/EdFi.Ods.Admin.Api/Features/Vendors/EditVendor.cs
- Application/EdFi.Ods.Admin.Api/Features/Vendors/ReadVendor.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/AdminApiEndpointBuilder.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/AdminApiVersions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/EndpointRouteBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationExtensions.cs
- Application/EdFi.Ods.Admin.Api/Program.cs
Future-proof Admin API endpoints by applying a `/v1` prefix to all feature endpoints.
- introduces a wrapper around `IEndpointRouteBuilder` to allow adjusting routes before mapping them
- supports registering an endpoint for multiple versions
- preserves ability to adjust routes by `RouteHandlerBuilder` extensions
- will ease some elements of AA-1544
- similar syntax to eventual support from .NET (probably)
- uses ASP.NET 6 versioning under the hood to prepare for future support
- `Connect` and `Information` (`/`) endpoints are _not_ versioned
- Root is not versioned
- Versioning for auth endpoints will ideally be simplified with future minimal API support from OpenIddict or ASP.NET versioning libraries
- Testing:
- E2E test collection updated for `v1` prefix
- Revert the final commit to …
> [AA-1543] Add Versioning to Admin API

- .github/workflows/promote-release.yml
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API.postman_environment.json
- Fixes issue that only allows to promote all packages at the same time.
- Update postman collection to remove references to old unused variable that makes the test fail when default user is not already present.
> [AA-1555] Allow to promote individual packages

- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.csproj
Reverted the upgrade to `Swashbuckle` packages to avoid the issue encountered due to version upgrade
More about the issue can be found at https://github.com/swagger-api/swagger-ui/issues/7911
> [AA-1559] - Fix for Swagger errors on POST and PUT endpoints

- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetResourcesByClaimSetIdQuery.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/ResourceClaim.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_ResourceEditor.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/resource-editor.js
Restores the "branch" `L`-looking icon which indicates child relationships when editing a claimset, previously missing when a child resource was added to an existing parent resource that had no children at load-time.
**The Fix**
Rather than try to re-organize newly added resources from the main dropdown to be under the appropriate category, I made a change to ensure the expand-arrow and "child" dropdown is present for _all_ parent resources (not just resources which have children saved on them already). This was straightforward in code since the query is split between parent and child resources already.
> [AA-1510] Claimset Relationship Display

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/build-package.ps1
- Update AppCommon version on build-package.ps1 to 3.0.0.
- Added the RequiredDotNetHostingBundleVersion variable with the value 6.0.0 set and passed it as a parameter for the updated AppCommon's Install-EdFiApplicationIntoIIS call.
- Switched on the IsCustomLogin flag on Add-SqlLogins calls.
> [AA-1513] - Update AppCommon on AdminApp Installer

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/AddVendorCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/EditVendorCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/AddVendorCommand.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/EditVendorCommand.cs
- Added an "empty string" check on AddVendorCommand and EditVendorCommand to avoid trying to add empty strings as namespace prefixes. These strings will simply be avoided.
- Added a call to "Trim" on EditVendorCommand to remove leading and trailing spaces and be in parity with AddVendorCommand.
- Added AddVendor and EditVendor unit tests to cover the "empty" namespace prefix case.
> [AA-1478] - Vendor NamespacePrefix Empty String fix

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/install.ps1
- EdFi.Suite3.Installer.AdminApp/test.ps1
- Added a validation check for ApiMode admin app feature. The installation exits if the api mode specified is not contained within the specified set of supported modes.Added a validation check for ApiMode admin app feature. The installation exits if the api mode specified is not contained within the specified set of supported modes.
- Refactored to use lowercase ApiMode settings to be in sync with the supported modes guidance.
> [AA-1395] - Add Validation for Api Mode on AdminApp Installer

- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/applicationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/vendorsPage.ts
Update search selectors to take the first element they find in the region. Now it happens not every time that it finds two selectors with the same name and the test fails.
This change should not affect running in a clean environment or one that already has data.
> AA-1572 Update command in order to select the firsts element in the screen

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
Remove .NET Core 3.1 installation step from Admin App Installer, as Admin App requires .NET 6 only.
Additionally, we plan to update `Installer.AppCommon` to change the function removed here to allow the .NET version to be specified as a parameter. We may also combine this with the check for the correctly installed version.
> [AA-1513] Remove .NET 3 Install

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiValidatorTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiValidator.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClientFactory.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/Services/SimpleGetRequest.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Added OdsApiValidator.cs to act as the validator service for ODS API and perform a JSON schema check for the configured ODS API Url.Added NJsonSchema package for JSON schema validation.
- Used IOdsApiValidator to validate the API before trying to communicate with the API using a client.
- Added unit tests for OdsApiValidator.cs.
> [AA-1374] - Validate ODS/API before trying to communicate with it

- Application/EdFi.Ods.AdminApp.Management.Tests/Configuration/Configuration/ApplicationConfigurationServiceTests.cs
- Application/EdFi.Ods.AdminApp.Management/Configuration/Application/ApplicationConfigurationService.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ProductImprovementController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/SetupController.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/FirstTimeSetupModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Setup/FirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Layout.cshtml
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
Introduces a new app settings flag which disables the "Product Improvement" configuration page and sets it to false.
- app settings flag defaults to `true`
- when flag is set to `false`:
- configuration always returns product improvement is disabled
- this handles scenario in which config was previously set to true,  before changing the flag
- bypasses first-time-setup config screen and sets configuration to false during initialization
- removes "⚙Configuration" link from layout and blocks direct access to page
> [AA-1556] Disable Product Improvement By Configuration

- Application/EdFi.Ods.AdminApp.E2E.Tests/gh-action-setup/set-versions.sh
Removes previous workaround needed before ODS/API upgraded to .NET 6. Now that that change is in place, this workaround is not only unneeded but causing our setup to fail.
> [AA-1579] Fix E2E Test Setup for ODS 6

- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.csproj
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
Downgraded AutoMapper (from 11.0.1 to 10.1.1) and AutoMapper.Extensions.Microsoft.DependencyInjection (from 11.0.0 to 8.1.1) packages as a temporary fix to the issue with LocalEducationAgencyReferenceResolver not being called during mapping.
> [ODST-214] - Fixes created school within some LEA not being displayed under that LEA

- Application/EdFi.Ods.Admin.Api/EdFi.Ods.Admin.Api.csproj
- Application/EdFi.Ods.AdminApp.Management/Api/Automapper/AdminManagementMappingProfile.cs
- Application/EdFi.Ods.AdminApp.Management/Api/Automapper/LocalEducationAgencyReferenceResolver.cs
- Application/EdFi.Ods.AdminApp.Management/Api/Automapper/StateEducationAgencyReferenceResolver.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
**NOTE: This is related to the temporary fix introduced in [ODST-214](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/332) and so warrants a test to the issue highlighted in that ticket as well.**
- Upgraded AutoMapper (to the latest 11.0.1) and AutoMapper.Extensions.Microsoft.DependencyInjection (to the latest 11.0.0) packages.
- Added static Resolve() overloads for LocalEducationAgencyReferenceResolver and StateEducationAgencyReferenceResolver.
- Added missing "CtorParam" mapping configuration to fix the Resolver not being called issues.
> [ODST-216] - Upgrade AutoMapper and Fix for LocalEducationAgencyReferenceResolver issue

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/AddClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/CopyClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetClaimSetByIdQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetClaimSetsByApplicationNameQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Configuration/Claims/CloudOdsClaimSetConfiguratorTester.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Queries/GetClaimSetNamesQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/AddClaimSetCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/CopyClaimSetCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetClaimSetByIdQuery.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetClaimSetsByApplicationNameQuery.cs
- Application/EdFi.Ods.AdminApp.Management/CloudOdsAdminApp.cs
- Application/EdFi.Ods.AdminApp.Management/Configuration/Claims/CloudOdsClaimSetConfigurator.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetClaimSetNamesQuery.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Upgraded Admin.DataAccess and Security.DataAccess packages to the latest versions.
- Updated Execute for GetClaimSetNamesQuery to include optional flags to exclude System Reserved and EdFi Preset claimsets. Added additional tests to validate the newly added flags. Updated the corresponding usage of the Execute method to avoid using the hardcoded SystemReservedClaimSets constant.
- Updated GetClaimSetsByApplicationNameQuery, GetClaimSetByIdQuery, AddClaimSetCommand and CopyClaimSetCommand   to use the new database flags instead of the hardcoded SystemReservedClaimSets and DefaultClaimSets constants. Updated the corresponding tests accordingly.
- Updated CloudOdsClaimSetConfigurator to explicitly set the new database flags while creating a claimset.
- Removed the unused …
> [AA-1507] - Remove hard-coded claimset names and use database flags

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/EditClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/GetApplicationsByClaimSetIdQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/EditClaimSetCommand.cs
- Added logic to re-associate applications to the renamed claimset.
- Added additional EditClaimSetCommand test to check vendor applications state after editing claimset.
> [AA-1594] - Re-associate applications with renamed Claimsets

- Application/EdFi.Ods.Admin.Api/Docker/DB-Admin/pgsql/Dockerfile
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/AddClaimSet.cs
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/DeleteClaimSet.cs
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/EditClaimSet.cs
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/ReadClaimSets.cs
- Application/EdFi.Ods.Admin.Api/Features/ClaimSets/ResourceClaimValidator.cs
- Application/EdFi.Ods.Admin.Api/mssql.Dockerfile
- Application/EdFi.Ods.Admin.Api/pgsql.Dockerfile
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/DeleteClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/EditClaimSetCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/DeleteClaimSetCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/EditClaimSetCommand.cs
**Code Fixes and Refactoring**
- Refactored to only show a single validation message for each distinct duplicate resource in the ResourceValidator.
- Refactored to throw the NotFoundException instead of validation failure exception to be similar to other not found cases for the endpoint.
- Refactored the EditClaimSet flow to throw an AdminAppException from within the claim set command and catch-rethrow a validation exception with the "System Reserved claim sets" exception message.
- Refactored the DeleteClaimSet flow to throw an AdminAppException from within the delete claim set command and catch-rethrow a validation exception with the "System Reserved claim sets" exception message.
- Added the additional condition to make sure the claimset exists when validating claimset …
> [ADMINAPI-34] - Adding e2e tests for claimsets endpoint

- .github/workflows/after-pullrequest.yml
- .github/workflows/on-pullrequest.yml
- build.ps1
Fixes to the OnPullRequest workflow found during improvements spike. Recreated from #363 commits directly for this repo instead of a fork in an attempt to get checks to pass correctly.
- fix C# test report paths to correctly capture artifact
- fix unit tests to not rebuild
- other cleanup:
- shorten or change names for "check" readability
- remove comments
The test reporter fix won't work until it's merged into main, since it happens after the pull request. I wonder if it is possible to determine if the PR source is from a fork, so we can take different paths for forks vs. not (not that it would help here)
> [AA-1628] Fix Test Report Paths + Optimize (Unforked)

- .github/workflows/on-merge-or-tag.yml
- .github/workflows/on-prerelease.yml
@pmcvtm @stephenfuqua 
Refactored all the set-output to $GITHUB_OUTPUT.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Thanks
> [AA-1608] Update Actions to use environment for state instead of set-output

- Application/EdFi.Ods.AdminApp.Management/Api/TokenRetriever.cs
- Docker/pgsql.Dockerfile
> [AA-1744] NET 8 - Update Restsharp - Token Serialization

- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site-form-handlers.js
Potential fix for [https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/security/code-scanning/222](https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/security/code-scanning/222)
To fix the issue, the regular expression used in `replace` should be updated to include backslashes (`\`) as part of the characters to escape. This ensures that all special characters, including backslashes, are properly escaped when constructing jQuery selectors. The updated regular expression will replace `(:|\.|\[|\])` with `([:\\.\\[\\]\\\\])`, where `\\\\` represents an escaped backslash.
The fix involves modifying line 174 to use the updated regular expression. No additional imports or dependencies are required.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 222: Incomplete string escaping or encoding

- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/SharingModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/AddClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetFileImportModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/CopyClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/EditClaimSetModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_AddClaimSet.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_CopyClaimSetModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_EditClaimSet.cshtml
Trim leading and trailing spaces in claim set names to ensure proper validation of existing claim sets
- Added validation in the client and server side
> [AA-1801] Trim leading and trailing spaces in claim set names to ensure proper validation of existing claim sets
