- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
@plioi @j-jordan @saa14 
Thanks
> [AA-1011] Bulk Upload is not working on Azure

- Application/Ed-Fi-ODS-Tools.sln
This PR adds references to top-level markdown files NOTICES.md, README.md, and CONTRIUBTORS.md in the 'solution folder' visible near the top of Solution Explorer, so that they are easy to access and edit from within the IDE.
> [AA-943] Include NOTICES, README, and CONTRIBUTORS in the solution folder

- Application/EdFi.Ods.AdminApp.Management.Tests/App.config
- Application/EdFi.Ods.AdminApp.Web.Tests/app.config
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Web.base.config
- Application/EdFi.Ods.AdminApp.Web/packages.config
@j-jordan @plioi @saa14 
Added missing Microsoft.ApplicationInsights.TraceListener package. Please help review and merge the changes.
Thanks
> [AA-1098] Azure 5.0.0 - Issue with long running hang fire jobs 

- .teamcity/_Self/Project.kt
Updated the TeamCity version parameter from 2.0.0 to 2.1.0 for Admin App.
> [AA-1704] Updated the TeamCity version parameter from 2.0.0 to 2.1.0 for Admin App

- Application/EdFi.Ods.AdminApp.Web/Helpers/InputFileExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/BulkRegisterOdsInstancesModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/BulkRegisterOdsInstances.cshtml
@j-jordan @saa14 @plioi 
https://tracker.ed-fi.org/browse/AA-1066
https://tracker.ed-fi.org/browse/AA-1056
Thanks
> [AA-1066] Bulk Register ODS - Add validation to column names to handle error

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
@j-jordan @plioi 
Please help review and merge the changes. Thanks
> [TSINSTALL-83] Error executing powershell installer when PostgreSQL is configured with SSPI

- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/BulkUploadValidationTests.cs
- Application/EdFi.Ods.AdminApp.Web.Tests/Controllers/OdsInstanceSettingsController/OdsInstanceSettingsControllerFixture.cs
- Application/EdFi.Ods.AdminApp.Web.Tests/EdFi.Ods.AdminApp.Web.Tests.csproj
- Application/EdFi.Ods.AdminApp.Web.Tests/packages.config
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/BulkUploadJob.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/BulkFileUploadModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstanceSettings/BulkLoad.cshtml
> [AA-1065] Improve application delete handler to consider bulk credentials

- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
> [AA-1065] Update response with bad request status and json error message.

- Application/EdFi.Ods.AdminApp.Management.Aws/LocalFileBasedGetCloudOdsHostedComponentsQuery.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/_Installers/OnPremInstaller.cs
- Using the data protection api from the System.Security.Cryptography.ProtectedData NuGet package that works for both net48 and netcoreapp3.1 instead of relying on the .NET Framework implementation.
- Using the caching api from the System.Runtime.Caching NuGet package that works for both net48 and netcoreapp3.1 instead of relying on the .NET Framework implementation.
- The code in this LocalFileBasedGetCloudOdsHostedComponentsQuery  is unreachable in an OnPrem environment and only accessible in the Aws environment and therefore, the LocalFileBasedGetCloudOdsHostedComponentsQuery class is being moved to Management.Aws from Management project
- Removed component registration for LocalFileBasedGetCloudOdsHostedComponentsQuery since it is not being used in the OnPrem …
> [AA-1092] - .NET Core compatibility for Management project's encryption, filesystem, and caching features

- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
- eng/run-dbup-migrations.ps1
@plioi @saa14 
1. Update the app common version to latest on Admin app installer
2. Set data base artifacts path on run-db-migration script conditionally between net48 and netcore
Thanks
> App common version update

- Application/EdFi.Ods.AdminApp.Web.Core/Views/GlobalSettings/Vendors.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/Home/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web.Core/Views/OdsInstanceSettings/SetupComplete.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/Vendors.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Home/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstanceSettings/SetupComplete.cshtml
Quick Fix to change Controller and action from settings action links in Old and New Admin App version
> AA-1147 Fix links to match recently-moved controller actions

- Application/EdFi.Ods.AdminApp.Web.Core/Views/Reports/_SelectDistrict.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Reports/_SelectDistrict.cshtml
Use another way to navigate between pages using razor html helpers with parameters
> [AA-1153] - Fix problem when browsing to Reports when using non default configuration

- .teamcity/_Self/templates/BuildAndTestTemplate.kt
- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.csproj
- Application/EdFi.Ods.AdminApp.Web.Core/EdFi.Ods.AdminApp.Web.Core.nuspec
- Application/EdFi.Ods.AdminApp.Web.Core/Startup.cs
- EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp-Core.psm1
- build.ps1
- eng/teamcity-get-package-version.ps1
@plioi @saa14 
Please help review and merge changes.
Thanks
> [AA-1140] Build .NET Core deployment package without affecting .NET Framework deployment package

- .gitignore
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/App.config
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests.csproj
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/Readme.md
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/SetUpFixture.cs
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/Testing.cs
- Application/EdFi.Ods.AdminApp.Management.Azure.IntegrationTests/appsettings.json
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Queries/Ods/OdsDataTestBase.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/Helpers/ConfigurationHelper.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Identity/Login.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/RegisterOdsInstance.cshtml
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- docs/cloudods-debugging.md
Fix styles issue with html action link helpers. It was fixed in:
Identity/Login.cshtml
OdsInstances/Index.cshtml 
OdsInstances/RegisterOdsInstance.cshtml
I reviewed over all  views and i considered that those were the only views that were missing for button styles
> [AA-1165] Fix styles issue with html action link helpers

- .teamcity/_Self/Project.kt
- .teamcity/_Self/buildTypes/PublishPackageToAzure.kt
- .teamcity/_Self/buildTypes/PublishPackageToAzureArtifacts.kt
> [AA-1189] Publish to azure artifacts

- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/LocalFileSystemFileUploadHandler.cs
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/signalr-progress.js
@stephenfuqua 
1. Updated GetWorkingDirectry method on "LocalFileSystemFileUploadHandler.cs " to return custom directory path (default directory value specified on appsettings)
2. Updated app setting "BulkUploadHashCache" to have default value (C:\\ProgramData\\Ed-Fi-ODS-AdminApp\\BulkUploadHashCache)
Thanks
> [AA-1130] PART1: Admin app docker file system writes - resolve bulk upload hash cache folder

- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_ResourceEditor.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/resource-editor.js
**What was happening?**
The button "Add resource" was enabled when nothing from resources list was selected and when user clicked button is was generating an error in console.
**What was the solution?**
First of all I disable the button until user selects a value from resources list and for the other side I added the validation  
"if (selectedItem.closest("optgroup")) "  to prevent the same null console error in case the user goes and manually edit the html to remove the disable button property.
> [AA-913 ]Fix issue with add resource button in claim set tab

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_AddSchoolModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_DeleteOrganizationModal.cshtml
-Attend Ticket AA-956 to adjust delete school/lea modal depending on the element that is removed. I added a logic to dynamically add correct title.
-Attend Ticket AA-869 to standardize confirmation messages, i did some changes to adjust the popup messages when adding, editing or removing a lea or school.
-I also included a JQuery fix to attend the issue creating schools. Because of a previously PR to attend the retained data after closing add school modal I introduced an issue assigning a new school to a lea, the parent ID was null.
> [AA-956] [AA-869] Adjust issues in Education Organization view

- Application/EdFi.Ods.AdminApp.Web/Properties/launchSettings.json
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Application/EdFi.Ods.AdminApp.Web/web.config
- Added explicit web.config with iis rewrite url section.
- Removed UseHSTS and UseHttpsRedirection entries from StartUp.cs file.
> [AA-1188] - IIS Rewrite module changes for AdminApp

- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site.js
Refactored to check for an undefined value before using it to set the scrolling parameter.
> [AA-1159]-JavaScript error logged when navigating away from claim sets

- EdFi.Suite3.Installer.AdminApp/install.ps1
- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
- EdFi.Suite3.Installer.AdminApp/test.ps1
> [AA-1218] Update AdminApp.web, AppCommon version update on AdminApp installer.

- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddLocalEducationAgencyModelTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Models/AddSchoolModelTests.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddLocalEducationAgencyModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/AddSchoolModel.cs
@saa14 @plioi 
Added validation rule for ensuring the School, LEA id uniqueness.
Thanks
> [AA-1208] Fix error message when school Id is already registered

- EdFi.Suite3.Installer.AdminApp/prep-installer-package.ps1
> [TSINSTALL-105] Update AppCommon version on Admin app installer

- .teamcity/_Self/Project.kt
- Upgrade Admin App version to 2.2.0 from 2.1.1
> [ODST-164] - Upgrade Admin App version to 2.2.0 from 2.1.1

- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/Index.cshtml
Ensure consistent and distinct Instance Index column headings regardless of API Mode.
> [AA-1274] Instance Listing Column Headers

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/Display/Pagination/PagedListAsyncTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/Display/Pagination/PagedListTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Queries/GetVendorsQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetVendorsQuery.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/VendorExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/GlobalSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/Display/Pagination/Page.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/ApplicationExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizationViewModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/AddVendorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/EditVendorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/VendorApplicationsModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Application/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Application/_Applications.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_EducationOrganizations.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site.js
- Added Page.cs and corresponding tests to handle server side paging functionality. This is similar to the DataImport paging functionality.
- Added HtmlHelperExtensions methods to create the html tags for the paging control.
- Added an overload for GetAll method to specify the starting offset and limit (number of items to get) to facilitate the paging flow by getting only the items to be displayed on the page. An extra item is added to indicate that more items are present to fetch.
**Education Organizations Tab Paging**
- Added GetLocalEducationAgenciesByPage method to facilitate paging on EducationOrganizations view.
- Refactored the EducationOrganizationViewModel to use the PagedList class for LocalEducationAgencies and added the LocalEducationAgenciesPageNumber to keep …
> [AA-960] - Use efficient paging controls when handling results from the ODS/API

- Application/EdFi.Ods.AdminApp.Management.Tests/Infrastructure/IO/WhenConfiguringFileImport.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/BulkUploadController.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/BulkImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/FileImportConfiguration.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/FileImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Jobs/BulkUploadJob.cs
> [AA-853] Enhance AA/ODS decoupling by using XSDs served up by ODS-4782

- Application/EdFi.Ods.AdminApp.Web/Controllers/GlobalSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/Views/GlobalSettings/Vendors.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/Index.cshtml
- Added DefineApplications() action to add data to TempData and refactored Vendors.cshtml to use DefineApplications action.
- Refactored OdsInstances/Index to add checks for TempData["VendorApplications"] and display the multi-instance guidance messages for application key/secret generation flow.
> [AA-1102] - Improve UX to get key/secret for multi instance mode

- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Application/EdFi.Ods.AdminApp.Web/appsettings.Docker-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- BuildDockerDevelopment.ps1
- build.ps1
@plioi @saa14 
Reference PRs:
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS/pull/245/files
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/pull/194
> [AA-1264] Update Admin App Virtual Endpoints Docker

- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/BulkImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/FileImportService.cs
> [AA-1278] Fix api server url to enforce backward compatibility

- Application/EdFi.Ods.AdminApp.Management.Tests/Configuration/Configuration/ApplicationConfigurationServiceTests.cs
- Application/EdFi.Ods.AdminApp.Management/Configuration/Application/ApplicationConfigurationService.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Models/ApplicationConfiguration.cs
- Application/EdFi.Ods.AdminApp.Management/Helpers/AppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/ActionFilters/AddTelemetryFilter.cs
- Application/EdFi.Ods.AdminApp.Web/Artifacts/MsSql/Structure/Admin/202104121100-AddEnableProductImprovementColumn.sql
- Application/EdFi.Ods.AdminApp.Web/Artifacts/PgSql/Structure/Admin/202104121100-AddEnableProductImprovementColumn.sql
- Application/EdFi.Ods.AdminApp.Web/Controllers/ProductImprovementController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/TrackerViewComponent.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/CloudOdsAdminAppSettings.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Telemetry.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ProductImprovementModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ProductImprovement/EditConfiguration.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ProductImprovement/EnableProductImprovementFirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Setup/FirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Setup/PostUpdateSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/Components/SingleInstanceCurrentYear/Default.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/Components/Tracker/Default.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Layout.cshtml
- Application/EdFi.Ods.AdminApp.Web/appsettings.Docker-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-DistrictSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-YearSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-DistrictSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-YearSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Content/css/Site.css
- Added migration scripts to add EnableProductImprovement column.Added EnableProductImprovement property to ApplicationConfiguration. Added methods to ApplicationConfigurationService to get the current status of the column and update the column value.
- Added ProductImprovementModel and ProductImprovementController to view and update the EnableProductImprovement column. The EnableProductImprovementFirstTimeSetup actions handle the view on the first time setup.
- Added EditConfiguration and EnableProductImprovementFirstTimeSetup views for the telemetry opt-in/opt-out screen.Used the ProductImprovementController actions during the first time setup to show the opt-in/opt-out screen. Refactored the Layout view to add the configuration icon next to the home icon to access the …
> [AA-1292] - Google Analytics enhancements

- Application/EdFi.Ods.AdminApp.Web/appsettings.json
Added the production GA property to the root appsettings.json GoogleAnalyticsMeasurementId appsetting.
> [AA-1288] - Add the Production Google Analytics property

- EdFi.Suite3.Installer.AdminApp/install.ps1
@plioi @saa14 
Update Admin App web package version to 2.2.0 on Admin app installer.
> [AA-1289] Update Admin App web package version to 2.2.0 on Admin app installer.

- .teamcity/_Self/Project.kt
@andonyns @saa14 @plioi 
Admin app version bump on team city build configuration after the release.
Thanks
> [AA-1289] Admin App version bump after 2.2.0 release

- Application/EdFi.Ods.AdminApp.Management/Api/InferExtensionDetails.cs
> [AA-1315] Infer TPDM extension enabled or not

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/OdsApiFacadeExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/AddApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Application/EditApplicationModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Application/_AddApplicationModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Application/_EditApplicationModal.cshtml
- Added TpdmEnabled and PostSecondaryInstitution fields to the AddApplicationModel.Added TpdmEnabled and PostSecondaryInstitution fields to the EditApplicationModel.
- Updated GetAllEducationOrganizations to include PostSecondaryInstitutions.
- Refactored the AddApplicationModal and EditApplicationModal to include PostSecondaryInstitutions.
- Refactored the Add and Edit actions for Applications to include PostSecondaryInstitutions and check for TpdmEnabled().
> [AA-1315] - Application view updates for TPDM

- EdFi.Suite3.Installer.AdminApp/install.ps1
- Update Admin App web package version to 2.2.1 on Admin app installer.
> [AA-1317] - Update Admin App web package version to 2.2.1 on Admin app installer.

- Application/EdFi.Ods.AdminApp.Web/Views/Application/_ApplicationsTable.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Content/css/Site.css
Refactored the Applications view display of ed-orgs to account for space on the section. Added additional css classes needed for the styling.
> [AA-1265] - Change display of list of EdOrgs when there are many in the list on Applications view

- Application/EdFi.Ods.AdminApp.Web/Controllers/HomeController.cs
Refactored to pass the setupCompleted bool to the Index action from the PostSetup redirection flow.
> [AA-1333] - Redirect from Enable Product Improvement to Register ODS Instance when there are no instances registered

- .gitignore
- EdFi.Suite3.Installer.AdminApp/EdFi.Suite3.Installer.AdminApp.nuspec
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
- EdFi.Suite3.Installer.AdminApp/upgrade.ps1
@stephenfuqua @plioi @saa14 
Please help review the changes.
> [AA-1331] Upgrade-Aware Installation

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
- EdFi.Suite3.Installer.AdminApp/upgrade.ps1
@saa14 
Please help review the changes. 
Thanks
> [AA-1360] After upgrade done, restart the IIS web site if it is in stopped state

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/test.ps1
> [ODST-184] Unable to Change Web Application Install Path

- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/NuGet.Config
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- build.ps1
- eng/database-manager.psm1
@saa14 
Thanks
Notes: EdFi.Admin.LearningStandards.Core 1.1.0 pushed to Azure Artifacts.
> [AA-1328] Upgrade Package Dependencies with ODS 5.3

- .teamcity/Installers/Project.kt
- .teamcity/Installers/buildTypes/BuildAdminAppInstaller.kt
- .teamcity/Installers/buildTypes/Deploy.kt
- .teamcity/Installers/buildTypes/PublishInstallerPackageToAzureArtifacts.kt
- .teamcity/Installers/buildTypes/ReleaseAdminAppPowershellInstaller.kt
- .teamcity/Installers/buildTypes/RepackageAdminAppInstallerAndPushToAzureBlobStorage.kt
- .teamcity/_Self/Project.kt
- .teamcity/patches/buildTypes/Deploy.kts
- .teamcity/settings.kts
Moving builds RepackageAdminAppInstallerAndPushToAzureBlobStorage and ReleaseAdminAppPowerShellInstaller into the Configuration as Code structure.
Update kotlin version
> AA-1304 Move builds into Kotlin structrure

- Application/EdFi.Ods.AdminApp.Management.Tests/Configuration/Configuration/OdsSecretConfigurationProviderTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/BulkRegisterOdsInstanceCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/BulkRegisterOdsInstancesRecordTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/GetOdsInstanceRegistrationsQueryTests.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/InstanceTestSetup.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Instance/RegisterOdsInstanceCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Models/OdsInstanceRegistration.cs
- Application/EdFi.Ods.AdminApp.Management/Instances/RegisterOdsInstanceCommand.cs
- Application/EdFi.Ods.AdminApp.Web/Artifacts/MsSql/Structure/Admin/202110220420-AddDatabaseNameColumn.sql
- Application/EdFi.Ods.AdminApp.Web/Artifacts/PgSql/Structure/Admin/202110220420-AddDatabaseNameColumn.sql
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstancesController.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/BulkRegisterOdsInstancesModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/IndexModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/OdsInstances/RegisterOdsInstanceModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/OdsInstances/Index.cshtml
@saa14 @pmcvtm 
Please help review and merge the changes. 
1. Updated Ods instance registration model to have new DatabaseName column for holding the associated db name
2. Update the instance to hold just instance id (district id or year)
3. Refactored model validation 
4. Added sql and postgresql migration scripts
Thanks
> [AA-1384] Find a method of referring to ODS Instances that allows longer then 50 character

- Application/EdFi.Ods.AdminApp.Management/Api/TokenRetriever.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/HomeController.cs
- Application/EdFi.Ods.AdminApp.Web/Helpers/HtmlHelperExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Home/ErrorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/Components/Tracker/Default.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/Error.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_ErrorFeedback.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Layout.cshtml
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site-form-handlers.js
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/site.js
- Added ErrorModel for the Error screens
- Moved the condition-based view components from the Error view to a partial in ErrorFeedback so that it can be used for AJAX errors as well.
- Refactored Error action in the Home Controller to use the Error Model and partial view for AJAX Errors.
- Refactored the LoadAsyncAction function to load the partial view result in case of Ajax errors. Moved the additional error message from the AjaxAction HtmlHelperExtension to the bearerTokenResponse errorMessage. Refactored the AjaxAction HtmlHelperExtension to remove the not-needed data attributes.
- Refactored the FieldValues() function to capture all the details (stack trace and status) from the Error view.
- Removed unused logger field from the HomeController as it was moved to the …
> [AA-1375] - Added UI for error handler

- Application/EdFi.Ods.AdminApp.Management.Azure/CompleteAzureFirstTimeSetupCommand.cs
- Application/EdFi.Ods.AdminApp.Management.OnPrem/CompleteOnPremFirstTimeSetupCommand.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Setup/CompleteOdsFirstTimeSetupCommandTester.cs
@andonyns 
Please help review and merge changes.
Thanks
> [AA-1834] Fill database name on shared instance mode

- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
@saa14 
Testing: General regression testing on Bulk upload feature. 
Thanks
> [AA-1369] Update Load tools package version to latest

- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetClaimSetsByApplicationNameQuery.cs
- Application/EdFi.Ods.AdminApp.Management/CloudOdsAdminApp.cs
Added "Education Preparation Program" to the list of default claimsets.
>  Add "Education Preparation Program" to the list of default claimsets

- Application/EdFi.Ods.AdminApp.Web/Views/ProductImprovement/EditConfiguration.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/ProductImprovement/EnableProductImprovementFirstTimeSetup.cshtml
- Application/EdFi.Ods.AdminApp.Web/appsettings.json
> [AA-1369] Update API analytics receive endpoint

- EdFi.Suite3.Installer.AdminApp/install.ps1
- EdFi.Suite3.Installer.AdminApp/upgrade.ps1
> [AA-1369] Update installer to have latest version

- .teamcity/_Self/Project.kt
- Release version update to 2.3.2 in order to prepare for the corresponding Docker release
> [AA-1404] - Release version update to 2.3.2

- EdFi.Suite3.Installer.AdminApp/install.ps1
- EdFi.Suite3.Installer.AdminApp/upgrade.ps1
- Updated Admin App package version to 2.3.2 from 2.3.1 for the admin app installer scripts.
> [AA-1404] - Updated Admin App package version to 2.3.2 from 2.3.1 for the admin app installer

- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/.eslintrc.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/.gitignore
- Application/EdFi.Ods.AdminApp.E2E.Tests/.vscode/extensions.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/.vscode/settings.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/README.md
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/login.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/functions.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/teardown.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/validators.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/adminAppPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/homePage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/loginPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/modelResolver.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/login.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/resultparser.py
- Application/EdFi.Ods.AdminApp.E2E.Tests/tsconfig.json
- Includes initial login test to guarantee that the tests are running.
> [AA-1410] Adding initial configuration of admin app e2e tests

- .github/workflows/e2e.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/login.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/adminAppPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/firstTimeSetupPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/homePage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/landingPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/loginPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/modelResolver.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/register.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/login.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
- Create login tests.
- Moving registration tests to its own file.
- Exclude registration tests from general execution.
- Fixing password on env.example file.
- If there's a failure on the execution, upload screenshots into execution.
> [AA-1414] Create login tests

- .github/workflows/e2e.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.gitignore
- Application/EdFi.Ods.AdminApp.E2E.Tests/reports/reports.md
- Application/EdFi.Ods.AdminApp.E2E.Tests/resultparser.py
- Modify python script to include more information about test execution such as execution that and exception message
- Use https://github.com/dorny/test-reporter to generate results from junit XML
> [ODST-198] Create report to get more information from test results

- Application/EdFi.Ods.AdminApp.E2E.Tests/features/educationOrganizations.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/functions.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/teardown.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/adminAppPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/educationOrganizationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/firstTimeSetupPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/homePage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/loginPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/modelResolver.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/productImprovementPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/educationOrganizations.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
This includes a set of test cases for Education Organizations, each test sets up and cleans its own data.
Tests:
- AA-859: Education Organizations section - Add Local Education Agency
- AA-860: Education Organizations section - Edit Local Education Agency
- AA-861: Education Organizations section - Delete Local Education Agency
- AA-862: Education Organizations section - Collapse Local Education Agency Section
- AA-934: Education Organizations section - Add Local Education Agency validations
- AA-1448: Education Organizations section - Add Duplicated Local Education Agency Id
> [AA-1425] Education Organization Tests

- Application/EdFi.Ods.AdminApp.E2E.Tests/features/educationOrganizations.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/login.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/functions.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/teardown.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/adminAppPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/applicationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/educationOrganizationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/loginPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/modelResolver.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/vendorsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/educationOrganizations.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/firstTimeSetup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/login.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/vendors.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/vendors.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
Includes scenarios for:
- Add vendor
- Edit vendor
- Delete vendor
- Help section
- Define applications
- Add vendor form validations and interaction
> [AA-1430] Vendors Tests

- .github/workflows/e2e-reports.yml
- .github/workflows/e2e.yml
- eng/send-test-results.ps1
- Move the script to the eng folder
- Added logging for more information
- Fix Admin App version
- Throw error if specified version is not found (This was currently adding the results to an unscheduled release, and this will make the results get lost into the executions)
> [AA-1504] Improvements to script to send result to Zephyr

- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/BulkUploadController/WhenRunningBulkUpload.cs
- Application/EdFi.Ods.AdminApp.Management.Tests/Controllers/EducationOrganizationsControllerTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/InferExtensionDetailsTests.cs
- Application/EdFi.Ods.AdminApp.Management/Api/InferExtensionDetails.cs
- Application/EdFi.Ods.AdminApp.Management/Api/InferOdsApiVersion.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/Services/SimpleGetRequest.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/BulkUploadController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/OdsInstanceSettingsController.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/BulkImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/IO/FileImportService.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/ProductRegistration.cs
- Application/EdFi.Ods.AdminApp.Web/Infrastructure/Telemetry.cs
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Application/EdFi.Ods.AdminApp.Web/_Installers/CommonConfigurationInstaller.cs
- Registered IHttpClientFactory using AddHttpClient in Startup.cs. Refactored InferOdsApiVersion and SimpleGetRequest to use HttpClient instead of WebClient.
- Added Microsoft.Extensions.Http to Management project.
- Refactored InferExtensionDetails to use the updated async method. Refactored InferExtensionDetailsTests due to the async/await updates in InferExtensionDetails.
- Refactored EducationOrganizationsController to use the updated async methods. Refactored associated unit tests.
- Refactored BulkUploadController to use the updated async methods. Refactored associated unit tests.
- Refactored ApplicationController, OdsInstanceSettingsController, ProductRegistration, and Telemetry to use the updated async methods.
- Refactored BulkImportService and FileImportService …
> [AA-1505] - Resolve warnings related to WebClient on AdminApp

- Application/EdFi.Ods.AdminApp.Management.Tests/ClaimSetEditor/ClaimSetFileImportCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/AuthorizationStrategy.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/ClaimSetFileImportCommand.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/Extensions/AuthorizationStrategiesExtension.cs
- Application/EdFi.Ods.AdminApp.Management/ClaimSetEditor/GetResourcesByClaimSetIdQuery.cs
- Application/EdFi.Ods.AdminApp.Web/Views/ClaimSets/_AuthStrategiesModal.cshtml
> [AA-1506] Claim set editor - claim set import not retaining the authorization strategy overrides (3.0)

- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/.gitignore
- Application/EdFi.Ods.AdminApp.E2E.Tests/.vscode/settings.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/applications.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/educationOrganizations.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/interfaces/index.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/functions.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/network.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/setup.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/management/teardown.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/adminAppPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/applicationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/educationOrganizationsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/loginPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/vendorsPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/applications.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/educationOrganizations.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/vendors.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/vendors.feature
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
- eng/send-test-results.ps1
- Add Application
- Delete Application
- Edit Application
- Regenerate Key/Secret
- Added function to track network calls and verify that expected request is executed.
- Updating dependencies
> [AA-1431] Applications Tests

- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API.postman_environment.json
- Application/EdFi.Ods.Admin.Api/E2E Tests/README.md
- Add README file
- Add collection with samples
> [AA-1464] Adding postman collection and environment for e2e tests

- .github/workflows/e2e-reports.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/.env.example
- Application/EdFi.Ods.AdminApp.E2E.Tests/gh-action-setup/set-versions.sh
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
**Do not active the E2E action until this PR has been merged**
- A previous update on the Alpine images broke the dependencies, therefore, we need to update the versions.
- Updating npm package versions
- Fixing issue that was posting the results of PR runs to Zephyr
> Update E2E And Docker dependencies

- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityExtensions.cs
- Application/EdFi.Ods.Admin.Api/appsettings.json
@pmcvtm 
Please help review and merge the changes. 
Thanks
> [AA-1528] - Admin API Not Decrypting Auth Tokens

- Application/EdFi.Ods.Admin.Api/Compose/pgsql/compose-build.yml
- Application/EdFi.Ods.Admin.Api/Compose/pgsql/env.example
- Application/EdFi.Ods.Admin.Api/Docker/mssql/env.example
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/appsettings.template.json
- Application/EdFi.Ods.Admin.Api/Docker/pgsql/env.example
- Application/EdFi.Ods.Admin.Api/E2E Tests/Admin API E2E.postman_collection.json
- Application/EdFi.Ods.Admin.Api/Features/FeatureConstants.cs
- Application/EdFi.Ods.Admin.Api/Features/Information/InformationModel.cs
- Application/EdFi.Ods.Admin.Api/Features/Information/ReadInformation.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/EndpointRouteBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Helpers/ConstantsHelper.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityConstants.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/Security/SecurityExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationBuilderExtensions.cs
- Application/EdFi.Ods.Admin.Api/Infrastructure/WebApplicationExtensions.cs
- Application/EdFi.Ods.Admin.Api/Program.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Management/Helpers/HealthCheckServiceExtensions.cs
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Startup.cs
- Adding health endpoint.
- Adding Docker configuration for health check.
- Returning JSON payload in landing page.
- Pretty printing JSON result.
- Adding postman test for root endpoint.
> [AA-1546] Admin API Root Page / Health Check

- Application/EdFi.Ods.Admin.Api/Features/Connect/ConnectController.cs
Fixes the Connect/Register `From` model binding attribute from `Body` to `Form` to match the content type of the action.
> [AA-1544] Fix 'From' Binding

- Application/EdFi.Ods.Admin.Api/mssql.Dockerfile
- Application/EdFi.Ods.Admin.Api/pgsql.Dockerfile
@saa14 
Please help merge the changes.
> [AA-1553] Update Admin Api package version

- Application/EdFi.Ods.Admin.Api/Compose/pgsql/compose-build.yml
- Application/EdFi.Ods.Admin.Api/Docker/DB-Admin/pgsql/Dockerfile
- Application/EdFi.Ods.Admin.Api/Docker/DB-Admin/pgsql/run-adminapi-migrations.sh
- Application/EdFi.Ods.Admin.Api/mssql.Dockerfile
- Application/EdFi.Ods.Admin.Api/pgsql.Dockerfile
@andonyns @saa14 
Please help review and merge the changes. 
Thanks
> [AA-1553] Create separate image for Admin Api data base tables setup

- .github/workflows/api-e2e.yml
- Application/EdFi.Ods.Admin.Api/Compose/pgsql/env.example
- Application/EdFi.Ods.Admin.Api/E2E Tests/gh-action-setup/.automation.env
Updating values for .automation.env and .env.example to have the expected value
> Updating env values for authority and issuer URLs

- Application/EdFi.Ods.Admin.Api/pgsql.Dockerfile
> [AA-1553] Update postgresql-client version

- Application/EdFi.Ods.Admin.Api/mssql.Dockerfile
@pmcvtm 
Please help review and merge the changes. Thanks
> [AA-1553] Update postgresql client version on mssql docker file

- EdFi.Suite3.Installer.AdminApp/install.ps1
Updates Admin App package version to release version for 2.4 in installer script.
> [AA-1567] Admin App Installer Update for 2.4

- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
@pmcvtm 
Please help review and merge the changes. 
Thanks
> [AA-602] Update DbDeploy version on Admin App installer

- .github/workflows/after-pullrequest.yml
- .github/workflows/e2e-reports.yml
Update test reporter version to address vulnerability. Merge only after https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Actions/pull/30
> [ODST-220] Update Test Reporter

- .github/workflows/on-prerelease.yml
- build.ps1
- docs/developer.md
- eng/package-manager.psm1
> [AA-1618] Issue with Admin App combined (Web and Installer) package creation

- Application/EdFi.Ods.AdminApp.Web/Startup.cs
**NOTE: This is a fix for Admin App corresponding to [the Data Import PR](https://github.com/Ed-Fi-Closed/Ed-Fi-DataImport/pull/378)**
Added basePath to the UserUnauthorized redirect path if it exists.
> [DI-1241] - Fix for User Unauthorized page redirect

- .github/workflows/on-merge-or-tag.yml
- .github/workflows/on-prerelease.yml
@pmcvtm 
Please help review and merge the changes. Thanks
> [AA-1608] GITHUB_OUTPUT fix PowerShell specific syntax

- Application/EdFi.Ods.AdminApp.Management/CloudOdsAdminApp.cs
- Application/EdFi.Ods.AdminApp.Web/Views/Home/Index.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/Shared/_Layout.cshtml
- README.md
> [AA-1647] Removes 'for Suite 3' out of Index and Layout

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- build.ps1
@jasonh-edfi 
Please help review and merge the changes. Copied changes from https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/371
Thanks
> [AA-1644] Replaced WebAdministration with IISAdministration module references.

- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiValidator.cs
- Application/EdFi.Ods.AdminApp.Management/AssessmentVendorAdjustment.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
@jasonh-edfi @lchavarriaga @jagudelo-gap 
Please help review and mere the changes. 
Thanks
> [AA-1655] Fix multiversion support for ODS API <= 5.1

- .github/workflows/on-prerelease.yml
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Application/EdFi.Ods.AdminApp.Web/Properties/launchSettings.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.Docker-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-DistrictSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.PostgreSql-YearSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-DistrictSpecific.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-SharedInstance.json
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-YearSpecific.json
- build.ps1
@jasonh-edfi @lchavarriaga @jagudelo-gap 
Thanks
> [AA-1654] PART1: Remove product improvement from build/ GH files

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- eng/database-manager.psm1
@jasonh-edfi @jpardogrowthaccelerationpartners 
https://tracker.ed-fi.org/browse/AA-1645
Thanks
> [AA-1645] Update db-deploy version

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- EdFi.Suite3.Installer.AdminApp/install.ps1
- build.ps1
@jpardogrowthaccelerationpartners @jasonh-edfi
> [AA-1663] Update version on Admin App install.ps1

- .github/workflows/aa-e2e.yml
- .github/workflows/e2e-reports.yml
@CSR2017 @jasonh-edfi You could review this PR. I tried the new toke on my fork and it's working. Change some parameters:
1. The file name was wrong so I couldn't upload the file to JIRA
2. Add a parameter to upload the results if it passes or fails in main
> [AA-1665] Update GitHub tokens for E2E reporting

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- EdFi.Suite3.Installer.AdminApp/Install-EdFiOdsAdminApp.psm1
- EdFi.Suite3.Installer.AdminApp/install.ps1
Modified OdsApiUrl param to be optional.
> [AA-1660] Modified OdsApiUrl  Param in install.ps1

- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/firstTimeSetupPage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/models/homePage.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/login.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/sharedSteps.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/features/support/vendors.ts
- Application/EdFi.Ods.AdminApp.E2E.Tests/gh-action-setup/compose-aa-build.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/gh-action-setup/set-versions.sh
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
@jpardogrowthaccelerationpartners @stephenfuqua 
Temporary fix for un-blocking the PRs.
Updating the ProductionOds database to EdFi_Ods on appsettings.template.json file using script.
Cherry picked @jpardogrowthaccelerationpartners commits from https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-AdminApp/pull/407
Thanks
> [AA-1688] Update ods connection string

- Application/EdFi.Ods.AdminApp.Web/Startup.cs
> [AA-1651] Fix the form value count limit

- .github/workflows/aa-e2e.yml
- .github/workflows/on-pullrequest.yml
- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
- Application/EdFi.Ods.AdminApp.Management.Tests/Database/Commands/EditApplicationCommandTests.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Commands/EditApplicationCommand.cs
- Application/EdFi.Ods.AdminApp.Web/appsettings.SqlServer-SharedInstance.json
Note that this pull request is into a branch called `v3.1.2-hotfix`, which was created from `v3.1.1`. When ready to release, create a tag `v3.1.2` from the hotfix branch. In `main`, change the tag to `v3.1.3`.
> [AA-1722] Fully reset EdOrgId's when editing application

- Docker/Compose/pgsql/compose-build-binaries.yml
- Docker/Compose/pgsql/env.example
- Docker/Settings/gateway/Dockerfile
- Docker/Settings/gateway/default.conf.template
- Docker/Settings/mssql/appsettings.template.json
- Docker/Settings/mssql/log4net.config
- Docker/Settings/mssql/run.sh
- Docker/Settings/pgsql/appsettings.template.json
- Docker/Settings/pgsql/log4net.config
- Docker/Settings/pgsql/run.sh
- Docker/Settings/ssl/generate-certificate.sh
- Docker/mssql.Dockerfile
- Docker/pgsql.Dockerfile
@stephenfuqua @jagudelo-gap @jasonh-edfi 
Thanks
> [AA-1724] Add Admin App docker files

- Application/EdFi.Ods.AdminApp.E2E.Tests/package-lock.json
- Application/EdFi.Ods.AdminApp.E2E.Tests/package.json
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- build.ps1
Update version:
- Chrome Driver from 103.0.0 to 121.0.0
- Axios from 0.27.2 to 1.6.7
- Follow Redirects from 1.15.1 to 1.15.5.
> [AA-1736] Update security packages in /Application/EdFi.Ods.AdminApp.E2E.Tests 

- .github/workflows/on-pullrequest.yml
- Application/EdFi.Ods.AdminApp.Web/Views/_ViewStart.cshtml
Include cshtml to the onPullRequest workflow
> [AA-1653] Trigger on-pullrequest workflow with cshtml files

- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetApplicationByIdQuery.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetApplicationsByVendorIdQuery.cs
- Application/EdFi.Ods.AdminApp.Management/Database/Queries/GetVendorsQuery.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
Add missing fields to fix is issues-
Update filter to remove Equals
> [AA-1737] Upgrade to NET 8 - Fixes

- Application/EdFi.Ods.AdminApp.Management.Tests/EdFi.Ods.AdminApp.Management.Tests.csproj
- Application/EdFi.Ods.AdminApp.Management.UnitTests/Api/OdsApiFacadeTests.cs
- Application/EdFi.Ods.AdminApp.Management.UnitTests/EdFi.Ods.AdminApp.Management.UnitTests.csproj
- Application/EdFi.Ods.AdminApp.Management/Api/IOdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
- Application/EdFi.Ods.AdminApp.Management/Api/TokenRetriever.cs
- Application/EdFi.Ods.AdminApp.Management/EdFi.Ods.AdminApp.Management.csproj
- Application/EdFi.Ods.AdminApp.Web/EdFi.Ods.AdminApp.Web.csproj
- Update  package version.
- Update code and test to match the new version.
> [AA-1744]  NET 8 - Update Restsharp to latest version

- Application/EdFi.Ods.AdminApp.Management/Api/OdsRestClient.cs
> [AA-1744] NET 8 - Update Restsharp - Token Serialization (Post and Put)

- Application/EdFi.Ods.AdminApp.Management/Api/TokenRetriever.cs
- Docker/pgsql.Dockerfile
> [AA-1744] NET 8 - Update Restsharp - Token Serialization

- .github/workflows/aa-e2e.yml
- .github/workflows/after-pullrequest.yml
- .github/workflows/e2e-reports.yml
- .github/workflows/on-merge-or-tag.yml
- .github/workflows/on-prerelease.yml
- .github/workflows/on-pullrequest-dockerfile.yml
- .github/workflows/on-pullrequest.yml
- .github/workflows/on-release.yml
- docs/developer.md
- Replace docker-compose by docker compose
- Update actions to replace deprecated versions
> [AA-1772]  Fix Admin App E2E Tests

- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/ClaimSets/ClaimSetFileImportModel.cs
> [AA-1784] Replace Obsolete PropertyName Usage in ClaimSetFileImportModel.cs

- Application/EdFi.Ods.AdminApp.Management/Api/IOdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Management/Api/OdsApiFacade.cs
- Application/EdFi.Ods.AdminApp.Web/Controllers/EducationOrganizationsController.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/EducationOrganizations/SchoolsByPsiViewModel.cs
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_AddPsiSchoolModal.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_LocalEducationAgencies.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_PostSecondaryInstitutions.cshtml
- Application/EdFi.Ods.AdminApp.Web/Views/EducationOrganizations/_SchoolsByPsi.cshtml
- Fix toggle error on pagination
- Update Post-Secondary Institutions  to include pagination similar to LocalEducationAgency version
> AA-1779 Admin App hangs when trying to pull the ed org list

- Application/EdFi.Ods.AdminApp.Web/Controllers/ApplicationController.cs
- Application/EdFi.Ods.AdminApp.Web/wwwroot/Scripts/bootstrap-multiselect.js
return bootstrap multiselect version to avoid compatibility errors with other libraries and add scapeHtml method to sanitize text
> [AA-1780] Return to bootstrap multiselect old version and add scapeHtml method

- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/AddVendorModel.cs
- Application/EdFi.Ods.AdminApp.Web/Models/ViewModels/Global/EditVendorModel.cs
Update models to include the email pattern validation
> [AA-1800] [Fix] Email Address Field in Vendor Maintenance Accepts Invalid Formats
